### PR TITLE
Emojis in Chat

### PR DESCRIPTION
**Pull request by elieserdejesus**
Supporting emojis in chat.

### CODE REVIEW

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , a nice 2018 for you and your family.

I'm finishing the **emojis** feature. 

**JamTaba Standalone sending emojis (unicode) to previous JT versions:**
emojis standalone x old jamtaba


**JamTaba sending emojis to ReaNinjam (unfortunally just a lot of ?????)**
emojis standalone x reaninjam

When a emoji is selected in the **emoji grid** you will see just a unicode emoji (ugly, small and black and white) in the chat text field.  Qt 5.7 is supporting colored emojis in fonts, but at moment I'm using an older Qt.

**Comment by jonjamcam** [comment]
Cool feature. Elieser I'm away from home until next week possibly. ATM I'm unable to compile and test.

**Comment by jonjamcam** [comment]
HNY for you too!

**Comment by elieserdejesus** [comment]
> Cool feature. Elieser I'm away from home until next week possibly. ATM I'm unable to compile and test.

no problem @jonjamcam,  enjoy your free time!

**Pull request merged**
