### PR TITLE
Matching icons and themes background colors

### PR DESCRIPTION
**Pull request by elieserdejesus**
- [x] New icons for preset actions: 
- [x] New little speaker icons
- [x] New MIDI icon

### CODE REVIEW

**Comment by jonjamcam** [comment]
nice!

**Comment by jonjamcam** [comment]
The Black theme's menu color will need some tweaking for the new icons:

image

The little black + and - are not showing right.

**Comment by elieserdejesus** [comment]
@jonjamcam , I changed the icons a little bit using a lighter border:
image

**Comment by jonjamcam** [comment]
ADD buttons still invisible n Black theme:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , I used your 2nd suggestion.

**Pull request merged**
