### PR TITLE
[WIP] Audio peak meter improvements

### PR DESCRIPTION
**Pull request by elieserdejesus**
- [x] paint RMS using the same segment approach used in peak values
- [x] allow audio peak meter **start** and **end** colors in CSS
- [x] meter plotting wrong values?

### CODE REVIEW

**Comment by jonjamcam** [comment]
Some other ideas:

1.- Choose another color for the _max peak_. Dark  red, for example?

2.- Other designs for inspiration (from google):

Notice how the peak hold is a button at the bottom:



And here there's a dual view with both meters (similar to reaper):



More buttons at the bottom:



And the rounded one:

**Comment by jonjamcam** [comment]
@elieserdejesus Looks to me the meters are not showing correct information when testing this PR:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , these meter pictures are very nice, but I choosed the most **simple to program at moment** approach, we can work in meters painting again in next versions.

Now is possible define CSS based colors in **General.css** for:
- max peak color
- audio peak start and end colors
- rms color

I changed the colors for some themes:
image

> Looks to me the meters are not showing correct information when testing this PR

I will check, possibly some wrong math in painting  code.

**Comment by elieserdejesus** [comment]
@jonjamcam , I fixed the wrong meter values. Can you check again before I merge this PR?

**Comment by jonjamcam** [comment]
Values ar OK now.

**Pull request merged**
