### PR TITLE
Using h264 codec in video streams

### PR DESCRIPTION
**Pull request by elieserdejesus**
@jonjamcam , can you test this PR in your machine? 

Is mandatory download the new [pre compiled libraries](https://www.dropbox.com/s/qckwsmaqlditwpb/JamTaba-static-libs.zip?dl=0). I recompiled FFmpeg libs and the h264 lib (libx264) using all optimizations.

I recommend these steps when testing:

1 - Compile the standalone (in release mode)
2 - Connect in a server using the compiled standalone and the previous version (2.1.4) VST plugin.
3 - Xmit the video from the VST plugin, your standalone will receive the poor encoded and low resolution video. The poor quality is easy to see using the grid layout.
4 - Now turn off the video in VST plugin and turn on the video in standalone. You will see the big difference in the video quality.

Here in my machine the cpu usage is very good, I suppose you will have no problem in your 2 cores computer.

### CODE REVIEW

**Comment by jonjamcam** [comment]
Huge difference in quality! Colors are much better, the movement is smoother:

image

**Comment by elieserdejesus** [comment]
> Huge difference in quality! Colors are much better, the movement is smoother:

Nice @jonjamcam , I'm very impressed with the quality of h264, is really a magic video codec. 

How is the cpu usage in your machine?

**Comment by jonjamcam** [comment]
> How is the cpu usage in your machine?

This is a test I need to make while jamming for it to be more accurate, but on the encoding part, just connecting to localhost and stream, a quick test shows:

image

 It is more or less an expected result.

**Comment by elieserdejesus** [comment]
thanks @jonjamcam , I will merge this PR, thanks for your help!

**Comment by elieserdejesus** [comment]
Hi @fab672000 and @pljones , this PR is using a **new libraries set**. The previous libs will not compile. Please download the new pre compile libs: https://www.dropbox.com/s/qckwsmaqlditwpb/JamTaba-static-libs.zip?dl=0 and enjoy the h264 video codec 😄

**Comment by fab672000** [comment]
Exciting improvement, thanks for the static libs!

**Pull request merged**
