### PR TITLE
Refactoring tests directory layout

### PR DESCRIPTION
**Pull request by teamikl**
- [x] fix some MinGW issue
   - c++11 flag for nullptr
 - [x] fix src/Common/ninjam/Server.cpp missing include header
 - [x] move manual tests to tests/manual
 - [x] add root project for auto tests (build-only)

The name `manual` was from Official Qt's tests repo layout.
they had naming `auto` `manual` `benchmarks` etc.

about the header include fix,
I am not sure I just add the fix to pass compile. please check this if it was wrong place.
It modified code under ./src so that may effects to main app projects.

### CODE REVIEW

**Comment by teamikl** [comment]
NOTE: check the tasklist when you check the task.
Owner can check it, right?

**Comment by elieserdejesus** [comment]
Tasks checked, nice work! I like the auto tests layout very mutch, it's easy run the tests now.

**Comment by elieserdejesus** [comment]
@teamikl , can I integrate this PR?

**Comment by teamikl** [comment]
@elieserdejesus 
> can I integrate this PR?

Yes  if there were checked and no problem. Please.

**Comment by elieserdejesus** [comment]
It's merged, thanks Tea!

**Pull request closed without merging**
