### PR TITLE
Fix big server name layout issues

### PR DESCRIPTION
**Pull request by elieserdejesus**
- [x] Drop server name from ninjam window
- [x] Improve chat messages layout to avoid issues with big user names.
- [x] Improve the text in Chat tab when the server is using a big name.
- [x] Add time stamp in chat messages

this PR solve the problems relatated in #318

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@teamikl and @jonjamcam , I changed the chat messages layout to avoid problems with big user names. This is the result at moment (tested in mini mode to have more size restrictions):

image

**Comment by elieserdejesus** [comment]
This is the visual test result:

image

**Comment by teamikl** [comment]
@elieserdejesus 
good improvement. then got the right of user name space, can use for time stamp.
If translate button was top-right then can remove the left dead space too.

about test code directory layout
the test code was manual test (it's for human looks the layout), it's not good to mix with unit tests.
e.g. assumed scenario is run all tests, app.exe() will block the test task.
manual test code can be another directory under ./tests.

just review for now. I will test tomorrow.

**Comment by teamikl** [comment]
I noticed the left space can stay as indent of paragraph.

**Comment by elieserdejesus** [comment]
@teamikl , I agree with the changes in tests dir layout. I will create another issue to this task.

**Comment by elieserdejesus** [comment]
Time stamps added in chat messages. @teamikl , I test the timestamp in top right but the layout is messed when the server name is big (ninjamers.serverbeer.com) and a server message is received. I put the timestamp in bottom, like facebook chat:

image

**Comment by elieserdejesus** [comment]
Tasks finished! I removed the server name from chat tab title to avoid a messed visual in big name servers. The "Chat <server name>" was changed to just "Chat". The server name is displayed in the ninjam window tab title, no need to duplicate the server name in chat title (at moment we have just one chat). 
image

**Comment by jonjamcam** [comment]
Is it possible to keep the chat boxes design? I think it was something special:

image

**Comment by elieserdejesus** [comment]
Good idea @jonjamcam. This is the result:
image

**Comment by jonjamcam** [comment]
yeah! that's nice!

**Comment by teamikl** [comment]
@elieserdejesus 
timestamp worked it's nice. thanks

about test dir layout, I will make PR

**Comment by elieserdejesus** [comment]
This PR is merged in master!

**Pull request closed without merging**
