### PR TITLE
Fix VstScanner build for OSX

### PR DESCRIPTION
**Pull request by fab672000**
With only one line change i could now use the Jamataba full build to regenerate all three executables now including the scanners.It seems to make sense to include the missing framework as it is already added in the standalone project in order to not have linkage errors, so now I am wondering how it could build without it for other users ?
Also can someone please build the OSX version to confirm it does not add any regression ?
Thanks in advance,
 
My Config:
OSX Sierra/Xcode9.2/Qt5.6.2/ eli static precompiled libs / custom ffmpeg build.

### CODE REVIEW

**Comment by elieserdejesus** [comment]
Hi @fab672000 , I'm 99% shure the VST scanner is compiled in windows only. Check https://github.com/elieserdejesus/JamTaba/blob/master/PROJECTS/Jamtaba.pro

In Mac only the AUScanner is compiled. 

Maybe I'm missing something?

**Comment by fab672000** [comment]
Yes you do :) please look again to your link Jamtaba.pro link and you will see that the *VSTPlugin*  is only win32 not the *VstScanner*.
```
win32{
    SUBDIRS += VstPlugin  #VstPlugin need Qt static build
}

```
Hope this helps, 
-Fab

**Comment by elieserdejesus** [comment]
Ops, you right @fab672000 . The VstScanner subdir is included in all platforms. 

I will check if the VstScanner.pro is compiling fine in my mac.

**Comment by elieserdejesus** [comment]
@fab672000 , I tested your change in my Mavericks and is compiling without problems too. 

Just checking: this PR contains some unrelated commits. Is the only relevant commit https://github.com/elieserdejesus/JamTaba/pull/971/commits/9b51a77aa8625d32162683d5d4244b48f8fdeb80 ??

**Comment by fab672000** [comment]
Yes I confirm it is the only one and the only that appears in the diff.
But for some reason that I don't understand yet,  the pull request workflow keeps showing us more (older) changes than I did yesterday (despite my committed and pushed merge with you yesterday).

**Comment by elieserdejesus** [comment]
> for some reason that I don't understand yet, the pull request workflow keeps showing us more (older) changes than I did yesterday

@fab672000 , are you **branching from master before write your changes** or are you **pushing directly in master branch?**

**Comment by fab672000** [comment]
I am committing then pushing directly in my forked master branch.
But I also realize than that my latest merge with you was pushed after this small change so maybe next pull request will show less. It does not matter for you integrate though as only one file should appear to be modified.

**Comment by elieserdejesus** [comment]
> I am committing then pushing directly in my forked master branch.

@fab672000, I will suggest an improvement in the workflow to keep the PRs more easy to review in my side. Just suggestions: 
1 - always write your changes in a local branch (branched from your master)

2 - Keep your master branch as a clone of the original repo. The sync your master branch is just **git pull**, and git always will do a **fast forward**, no extra merge commits will be added.

3 - When your changes are finished (in your local branch) push your local branch to your fork.

4 - Create the PR from your pushed branch in the fork.

In general the final result (merged commits) is the same, but keeping the PR commits clean it's easy to review, and to avoid undesired merge conflicts.

To integrate this PR I will cherry-pick the relevant commit. Thanks for the contribution!

**Comment by elieserdejesus** [comment]
merged in https://github.com/elieserdejesus/JamTaba/commit/021cc1a12f89c1c22d6a914b62edc91afd6ea8d4

**Comment by fab672000** [comment]
will definitly check this branch model out next time, thanks Eli.

**Comment by elieserdejesus** [comment]
thanks for you @fab672000 , you are always welcome!

**Pull request closed without merging**
