### PR TITLE
[Looper] Make looper start from the focused layer in sequence mode

### PR DESCRIPTION
**Pull request by elieserdejesus**

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , in this PR I implemented the idea discussed in #784. Now is possible start the sequence in the focused layer. Now is possible change the current playing layer in sequence mode. I like this behavior, is possible change the current layer in any moment and the sequence will continue from focused layer.

what do you think?

**Comment by jonjamcam** [comment]
@elieserdejesus I see the layer selection works while playing (similar to slelcted layer mode). The problem (for me) is now I can't select the recording layer without interrupting the normal looper flow. 

I think we can keep this behavior, but change the "recording focus" to double click so we can access both features differently

**Comment by elieserdejesus** [comment]
> The problem I have with the ability to change the playing layer in the middle (as this PR proposes) is that now you can interrupt (willingly or by mistake) one layer at any point and this can lead to non-musical results.

Perfect @jonjamcam , I'm convinced.

**Comment by elieserdejesus** [comment]
@jonjamcam , I pushed a commit in this PR allowing layer selection only when looper is stopped.

**Comment by jonjamcam** [comment]
Works great. Thx @elieserdejesus .

**Pull request merged**
