### PR TITLE
Fix missing override keywords in 13 include files inside src/Common and few other warnings on OSX

### PR DESCRIPTION
**Pull request by fab672000**
Fixes missing override keywords in many src/Common include files in order to avoid warnings when building with MacOSX and CLang >= 7.0

### CODE REVIEW

**Comment by elieserdejesus** [comment]
Hi @fab672000 , I see this PR contains some old commits. To avoid unexpected merging issues in master branch I manually added your commits in the master.

Thanks for the contributions!

**Comment by fab672000** [comment]
sorry about the merge, I used a develop branch this time first then merge to my master branch only before i would submit a pull request. not sure why it happens, how can I rest my master branch so that it is exactly in sync with yours ?

**Comment by elieserdejesus** [comment]
@fab672000 , maybe this can help you: https://help.github.com/articles/syncing-a-fork/

**Comment by elieserdejesus** [comment]
@fab672000 , I think this is better for your case: https://gist.github.com/glennblock/1974465

**Comment by fab672000** [comment]
Thanks I finally sorted it out i read the same article and did a hard reset but then github remote branch would only sync after this forcing added command:
git push origin +master
it saved my day :)

**Pull request closed without merging**
