### PR TITLE
Ice theme

### PR DESCRIPTION
**Pull request by jonjamcam**

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , I have some little reviews to this PR:

1 - I received some warnings about duplicated aliases in the resources file:
```
..\..\JamTaba\src\resources\jamtaba.qrc: Warning: potential duplicate alias detected: 'BaseTrack.css'
..\..\JamTaba\src\resources\jamtaba.qrc: Warning: potential duplicate alias detected: 'Chat.css'
..\..\JamTaba\src\resources\jamtaba.qrc: Warning: potential duplicate alias detected: 'Chords.css'
..\..\JamTaba\src\resources\jamtaba.qrc: Warning: potential duplicate alias detected: 'Dialogs.css'
..\..\JamTaba\src\resources\jamtaba.qrc: Warning: potential duplicate alias detected: 'General.css'
..\..\JamTaba\src\resources\jamtaba.qrc: Warning: potential duplicate alias detected: 'LocalTrack.css'
..\..\JamTaba\src\resources\jamtaba.qrc: Warning: potential duplicate alias detected: 'MainWindow.css'
..\..\JamTaba\src\resources\jamtaba.qrc: Warning: potential duplicate alias detected: 'NinjamWindow.css'
..\..\JamTaba\src\resources\jamtaba.qrc: Warning: potential duplicate alias detected: 'PublicRooms.css'
```

The problem is in **line 493** in **jamtaba.qrc file**. Please delete these duplicated lines. The *original* lines are declared in **line 53**, the correct place.

2 - I started the Ice theme based in Volcano files. I think some borders are too "orange", using the volcano pallete. Please check the attached image.

3 - In my eyes the bottom and content panel colors are not matching enough. It's not bad, but is not cool like other themes. Can you try another colors in content and bottom panels?

image

**Comment by jonjamcam** [comment]
One idea for the bottom and content panels:

image

image

[Ice_exp1.rar.txt](https://github.com/elieserdejesus/JamTaba/files/709914/Ice_exp1.rar.txt)

**Comment by jonjamcam** [comment]
@elieserdejesus I took my chances and pushed some changes in https://github.com/elieserdejesus/JamTaba/pull/663/commits/c53949321ef2a95ec0db5184c9376562477b3bbe based on Ice_exp1b2. Hope you like the result :D

**Comment by elieserdejesus** [comment]
@jonjamcam  it's very nice now, thanks for this job.

It's finished? Can I merge the PR?

**Comment by jonjamcam** [comment]
>It's finished?

Opps, not yet. Just noticed I did not change the "orange borders".

**Comment by jonjamcam** [comment]
@elieserdejesus It's complete now.

**Comment by jonjamcam** [comment]
sry 4 that. You know sometimes you fix one part and other breaks down. 

I revised it now and it's finished :D.

**Comment by elieserdejesus** [comment]
@jonjamcam , the xmit button border is nice now. 

Can I merge the PR?

**Comment by jonjamcam** [comment]
>Can I merge the PR?

please do :D

**Comment by elieserdejesus** [comment]
merged, thanks @jonjamcam !

**Pull request merged**
