### PR TITLE
Fixing input text styles colors for all themes [VST plugin]

### PR DESCRIPTION
**Pull request by jonjamcam**
- [x] Fixing local channel name background color when focused.
- [x] Match Local track channel name's border from standalone and VST plugin when focused.
- [x] Match input text dialog borders stdlne and VST
- [x] Fix chat background color when focused.
- [x] Fix panelcombos background color when focused.
- [x] Fix ninjampanel Comboboxes background color when focused.
- [x] Use different colors for all new qlinEditentries.
- [x] correct white font color in black theme when focus

### CODE REVIEW

**Comment by jonjamcam** [comment]
@elieserdejesus I'm stuck with these two tasks:

It looks the QlineEdit colors are cloned into the panel combo boxes and the chat when focused:

image

image

I could fix the local channels OK, but I had to change a some of the borders from the original work. And because I couldn't separate the above colors I think it's not a good result at the moment.

I tried QlineEdit in many combinations. It worked with the local tracks, but didn't with the rest.

If there is no other choice I can tweak the palette to make it better, but please do not merge Yet.

**Comment by elieserdejesus** [comment]
@jonjamcam , these colors problems are related with the "text editor trick" I'm  using in VST to avoid key stroke problems. 

I'm changing (again) the "text editor trick code" a lot to solve #694, and Pipaxis reported some problems in Mac too, so I suggest keep this PR in standby until I solved these text editors annoying problem.  

At moment I'm trying a different (more simple) approach using just a cloned QLineEdit, maybe this new approach will cause less side effects in CSS colors.

**Comment by elieserdejesus** [comment]
@jonjamcam , I fixed the #694 . To get the changes in this PR branch you need run
```
// 1- go to your branch
 git checkout input-text-color-style-fixes 

// 2 - merge master branch in your branch. This merge will put the last commit in master in your branch
git merge master
```
***
Now, in VST/AU plugin I'm using a cloned QLineEdit in every  QLineEdit (combo boxes are using internal QLineEdits too). These cloneds QLineEdit are using the original **objectName** plus a **-topLevel** suffix. I addopted this suffix idea to allow custom colors for these *hacked* QLineEdits. For example:
image

I suggest you use some different color (similar to current behavior) to keep clear when the QLineEdit is focused and editable. This is important because sometimes is necessary click 2 times in these hacked line edits.  It's a pain get these cloned input fields behaving correctly when focus change. In Standalone these "different colors" are not necessary.

**Comment by jonjamcam** [comment]
@elieserdejesus I'll have to wait for the next beta release to see the corrections in the VST plugin. My QT compiles only the standalone version.

>I suggest you use some different color (similar to current behavior) to keep clear when the QLineEdit is focused and editable.

OK. I do that.

**Comment by elieserdejesus** [comment]
@jonjamcam , I released a new beta.

**Comment by jonjamcam** [comment]
@elieserdejesus Trying to use the new format, but I'm not having results with the chat text, for example in _chat.css_:

`ChatPanel #chatText:focus`

I added the line:

`ChatPanel #chatText:focus,
ChatPanel #chatText-toplevel:focus `

but doesn't work. Using:

`ChatPanel #chatText:focus,
ChatPanel #chatText-toplevel `

it doesn't work either.

**Comment by elieserdejesus** [comment]
@jonjamcam , **ChatPanel #chatText** means "a widget ChatPanel containing a child widget named as chatText".  The "cloned" text input fields are not inside any widget hierarchy. 

Try just 

```
#chatText-topLevel
```
or
```
QLineEdit#chatText-topLevel
```

**Comment by jonjamcam** [comment]
K. Got it. Last question: the Panelcombos qlinedit has the same syntax? I tried:

`QLineEdit#panelCombos-topLevel`

Trying to fix:



but has no effect.

**Comment by elieserdejesus** [comment]
@jonjamcam , this one is more trick because the QLineEdit is a hidden child in the combo box. I changed the code to add the -topLevel suffix in the combo line edit. The syntax is:
```
#comboBpi-topLevel,
#comboBpm-topLevel
{
	background-color: red;
}
```
The VST plugin compiled with the last commit adding the -topLevel suffix:

[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/756012/JamtabaVST2.zip)

**Comment by jonjamcam** [comment]
Thx, @elieserdejesus . now I can finish this PR. Previously you wanted these "Top Qlinedits" to have a distinctive color. Do you want the same behaviour for the panelcombos and the chat text?

**Comment by elieserdejesus** [comment]
@jonjamcam , I think use different color will work for combos too, but please feel free to experiment.

**Comment by jonjamcam** [comment]
@elieserdejesus I finished the first part of the PR: that is match the new qlineEdit colors for the VST plugin with the same old ones from the standalone.

 The next step is to start the diferentiation, but I have a problem before doing that: I can't control some borders. Specifically the **local tracks channel name border** and the **chat input text border**. Looks like the new qlineEdit layer is making the borders dissapear.

Is it possible for these new QlineEdit code to be "borderless" or to be able to control the border via styles? I tried the `border: none;` code but it won't work.

NOTE: this PR will not compile because it has missing all .qm files for the translation. You'll have to use **lrelease**.

**Comment by elieserdejesus** [comment]
> Looks like the new qlineEdit layer is making the borders dissapear.

This is true @jonjamcam, I was hardcoding the new QLineEdit borders to solve some problems. I removed the hardcoded borders in last commit. You can merge master in your branch to get this commit.

This is the plugin compiled with the last changes:

[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/757062/JamtabaVST2.zip)

**Comment by jonjamcam** [comment]
@elieserdejesus Now that I got about 99.99% color match between the VST and the Standalone I'm thinkning about using this kind of gradient for the differentiation. What do you think?

image

but a bit more subtle.

**Comment by elieserdejesus** [comment]
@jonjamcam , I like these gradients, specially the first option in Ice theme.

**Comment by jonjamcam** [comment]
@elieserdejesus for Panelcombos I'm using a horizontal gradient:

image

image

**Comment by elieserdejesus** [comment]
nice smooth borders @jonjamcam !

**Comment by jonjamcam** [comment]
@elieserdejesus I finish the task, but it needs some fine tuning. Maybe rethink the chattext type of gradient? What do you think?

[All Themes PR 699 .rar.txt](https://github.com/elieserdejesus/JamTaba/files/758917/All.Themes.PR.699.rar.txt)

**Comment by elieserdejesus** [comment]
@jonjamcam , tested the changes here. I like all changes, but honestly the chat text gradient is too much in my eyes. The gradient is using a darker tone in top and bottom. The resulting effect is a height decrease in chat text input (if you compare with non focused version). In general focused fields are more "lighted" or bigger, to catpture user attention. I see (in Volcano, for example) the opposite effect (focused field looks "smaller"). 

I see you are using a bright color in gradient center and a more dark tone in top and bottom. I think this contrast (bright in center and dark in top/bottom) is too much. Can you try not too darker tones in top/bottom? I think the general idea I'm trying to propose is "reduce contrast in gradient internal colors'.

**Comment by jonjamcam** [comment]
>  I think the general idea I'm trying to propose is "reduce contrast in gradient internal colors'.

Yeah. I was not that convinced too. Let me try another approach. The kind of "Back spotlight" I used in the other fields for the chat text.

image

image

**Comment by elieserdejesus** [comment]
perfect @jonjamcam , this "back spotlight" idea is nice.

Job done? can I merge this PR?

**Comment by jonjamcam** [comment]
> an I merge this PR?

Yes. I think it's OK to merge.

**Comment by elieserdejesus** [comment]
thanks @jonjamcam !

**Pull request merged**
