### PR TITLE
wider Jamroomview top panel to allow bigger server names

### PR DESCRIPTION
**Pull request by jonjamcam**
image

### CODE REVIEW

**Comment by elieserdejesus** [comment]
Nice @jonjamcam! 

I loose my dev environment (my very old laptop is dead) and can't test until setup a new machine.

*One idea*: maybe put the listen and enter buttons in 2 rows (now these buttons are using 2 collumns)?

**Comment by jonjamcam** [comment]
> I loose my dev environment (my very old laptop is dead) 

That's sad to hear @elieserdejesus . Best wishes and I hope you recover it soon

> One idea: maybe put the listen and enter buttons in 2 rows 

I'll test that idea, but I believe the buttons at this size will not fit. Anyway there's plenty of time until you get a new computer :cry:

**Comment by jonjamcam** [comment]
after adjusting text spacing:

image

**Comment by jonjamcam** [comment]
final comparison:

image

Hope you like it. PR complete.

**Comment by jonjamcam** [comment]
> I can't test at moment. The new layout is ok in the other themes?

In my system it works fine in all themes, but no hurries @elieserdejesus . I would like you to take a look as always before merge.

**Comment by elieserdejesus** [comment]
>  it works fine in all themes
It's enough @jonjamcam , let's merge!  Thanks!

**Comment by elieserdejesus** [comment]
> @elieserdejesus Here's the vstplugin

Thanks @jonjamcam , Vst PLugin working fine here in all themes. 👍

**Pull request merged**
