### PR TITLE
A new Korean translation TS file added

### PR DESCRIPTION
**Pull request by soulraymusic**
This is the Korean translation version 1.0.

### CODE REVIEW

**Comment by elieserdejesus** [comment]
Hi @soulraymusic , I can't merge your file directly becayse github is pointing a lot of conflicts.

I can download your file, replace the old one and just commit and push, but your name will not be listed as a contributor (bad).

So, can you try solve this conflict in your side and create a new pull request?

**Comment by soulraymusic** [comment]
> Hi @soulraymusic , I can't merge your file directly becayse github is pointing a lot of conflicts.
> 
> I can download your file, replace the old one and just commit and push, but your name will not be listed as a contributor (bad).
> 
> So, can you try solve this conflict in your side and create a new pull request?

Yes, I will try it now!

**Comment by soulraymusic** [comment]
@elieserdejesus conflicts resolved. What is the next step?

**Comment by elieserdejesus** [comment]
> @elieserdejesus conflicts resolved. What is the next step?

Thanks @soulraymusic , I will merge your translation and generate the other files. Your contribution is done!!!! Thanks again!

**Comment by elieserdejesus** [comment]
@soulraymusic , The Korean translation menu entry is showing **(C)**.
Is it ok?
image

**Comment by elieserdejesus** [comment]
@soulraymusic , problem is solved. The correct name of Korean translation file is ko_KR.ts. The old file was **kr_KR.ts**, not a valid locale.

It's fixed now:
image

**Pull request merged**
