### PR TITLE
[WIP] Showing users in world map

### PR DESCRIPTION
**Pull request by elieserdejesus**
- [x] Show public room player in a world map widget
- [x] Show wave form layered in the world map
- [x] Change the public room big buttons
- [x] Avoid overllaped user names

### CODE REVIEW

**Comment by jonjamcam** [comment]
Hi @elieserdejesus nice feature. I found some details worth review:

Sometimes lines do not appear correctly:

image

When not maximized the rooms do not show all the information (need scroll):

image


and I found the world map does not match the black theme palette:

image

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , I solved the horizontal problem changing the position of public room infos (bpi, bpm, users count).

The world map is a collection of little images from **Open Street Maps**. For example: [http://tile.openstreetmap.org/1/0/0.png](http://tile.openstreetmap.org/1/0/0.png). I pushed a commit using a "night mode" trick in maps when using the Black theme. 

About the "lines not appearing", can you check again? I fixed this problem in last commits, maybe you tested without these last commits?

**Comment by jonjamcam** [comment]
All good now. Nice trick!

image

**Comment by jonjamcam** [comment]
@elieserdejesus I found sometimes usernames overlap in the map, space not being a problem.

image

**Comment by elieserdejesus** [comment]
Ok @jonjamcam , I will change the big buttons.

Another case to test overllaped player names:
image

**Comment by jonjamcam** [comment]
@elieserdejesus what do you think about reducing the size of the position point:

I tried 1.6 here:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , I changed the markers size to 1.6, looks good to me too.

**Pull request merged**
