### PR TITLE
Improving chat

### PR DESCRIPTION
**Pull request by elieserdejesus**
- Improving vertical space usage in chat messages
- Improving auto scroll behavior in chat

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam and @Hitrate , I'm improving the chat in 2 ways:
1 - Improving vertical space usage in chat messages
2 - Improving auto scroll behavior in chat

I deleted the "time stamp" in chat messages and reduced the "dead" vertical space. The timestamp is not too usefull in JamTaba because in general we have a messages burst after a cool jam, and the time stamps are very similar. This is the result:
image

In these changes the auto scroll will be skipped if user is reading the "old" chat messages. I'm "detecting" if user is reading or not the old messages checking the chat scroll bar position. If the scroll bar is in max bottom position I'm assuming user is reading the last/newest messages and the chat will auto scroll. Any other position in the scroll bar will disable the chat auto scroll (user is reading some old message).

What you think about?

**Comment by jonjamcam** [comment]
Nice @elieserdejesus ! 

All themes look great, but the rounded theme looks a little crowded:

image

**Comment by jonjamcam** [comment]
> Any other position in the scroll bar will disable the chat auto scroll (user is reading some old message).

I think this is OK, but chat position should be restored to last normal scrolling when you start typing again. It's very common behavior to scroll up o search for something and leave the scroll bar in a midway position

**Comment by elieserdejesus** [comment]
Done @jonjamcam , fixed the Rounded theme and auto scrolling when user is typing new messages.

**Comment by jonjamcam** [comment]
> fixed the Rounded theme and auto scrolling when user is typing new messages.

Behavior is good now. cool!

**Comment by Hitrate** [comment]
Looks good :) Is there a link to the latest beta so I can see it in action ? :)

**Comment by jonjamcam** [comment]
> Is there a link to the latest beta so I can see it in action ? :)

no new beta yet, but I second the motion for a new beta :smile:

**Comment by elieserdejesus** [comment]
@jonjamcam and @Hitrate , I will fix the issue #858 and release a new beta (I hope the last one 😄 ).

**Pull request merged**
