### PR TITLE
Revert "Fix QWaitCondition warning by separate thread"

### PR DESCRIPTION
**Pull request by teamikl**
Reverts elieserdejesus/JamTaba#189

The patch had problems.
Since the task was low priority, does not need it now.
no debug, just revert to clean master.

### CODE REVIEW

**Comment by teamikl** [comment]
Ah so qucik!
I was going to write tasks before merge, now.

- [ ] build debug mode
- [ ] test enter ninjam room and leave the room

**Comment by teamikl** [comment]
It's ok I will test these now.

**Comment by elieserdejesus** [comment]
Tested here, working.

**Comment by teamikl** [comment]
To test the encoding thread working, had to wait 3 intervals. It ok same here.

**Pull request merged**
