### PR TITLE
Feature/metronome accent patterns

### PR DESCRIPTION
**Pull request by pljones**
OK, that looks a lot better in terms of the pull request commits.

It's still not building here, though, even with ` -lMfplat` or ` -Mfplat` (or, indeed, both) added to LIBS.

The failure seems to relate to various symbols  from `evr` object files - presumably related to `qtCompileTest(evr)` in the `qtmultimedia.pro` project file.  The symbols it fails on are all related to `presenter`, like:
```
dsengined.lib(evrcustompresenter.obj) : error LNK2001: unresolved external symbol MF_MT_FRAME_RATE
...
dsengined.lib(evrd3dpresentengine.obj) : error LNK2019: unresolved external symbol DXVA2CreateDirect3DDeviceManager9 referenced in function "private: long __cdecl D3DPresentEngine::initializeD3D(void)" (?initializeD3D@D3DPresentEngine@@AEAAJXZ)
```

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@pljones , I'm suspecting (from D3DPresentEngine error) your qt multimedia is trying to link DirectX stuff. 
I'm guessing I have no errors here because I don't have DirectX installed in my machine. 

This is the result of the **configure** command (executed in Qt 5.5.0 sources) in my machine. As you can see the **QPA Backends** is showig no support for **Direct2D**.  

```
Configuration:
    pcre
    debug
    compile_examples
Qt Configuration:
    minimal-config
    small-config
    medium-config
    large-config
    full-config
    debug_and_release build_all release
    debug
    shared
    zlib
    angle
    png
    freetype
    harfbuzz
    build_all
    accessibility
    opengl
    opengles2
    egl
    audio-backend
    wmf-backend
    native-gestures
    qpa
    concurrent

QMAKESPEC...................win32-msvc2013 (env)
Architecture................x86_64, features: sse sse2
Host Architecture...........x86_64, features: sse sse2
Maketool....................nmake
Debug build.................yes (combined)
Default build...............debug
Force debug info............no
C++11 support...............auto
Link Time Code Generation...no
Accessibility support.......yes
RTTI support................yes
SSE2 support................yes
SSE3 support................yes
SSSE3 support...............yes
SSE4.1 support..............yes
SSE4.2 support..............yes
AVX support.................yes
AVX2 support................yes
NEON support................no
OpenGL support..............yes
Large File support..........yes
NIS support.................no
Iconv support...............no
Evdev support...............no
Mtdev support...............no
Inotify support.............no
eventfd(7) support..........no
Glib support................no
CUPS support................no
OpenVG support..............no
SSL support.................no
OpenSSL support.............no
libproxy support............no
Qt D-Bus support............no
Qt Widgets module support...yes
Qt GUI module support.......yes
QML debugging...............yes
DirectWrite support.........no
Use system proxies..........no

QPA Backends:
    GDI.....................yes
    Direct2D................no

Third Party Libraries:
    ZLIB support............qt
    GIF support.............plugin
    JPEG support............plugin
    PNG support.............yes
    FreeType support........yes
    Fontconfig support......no
    HarfBuzz support........qt
    PCRE support............qt
    ICU support.............no
    ANGLE...................yes
    Dynamic OpenGL..........no

Styles:
    Windows.................yes
    Windows XP..............yes
    Windows Vista...........yes
    Fusion..................yes
    Windows CE..............no
    Windows Mobile..........no

Sql Drivers:
    ODBC....................no
    MySQL...................no
    OCI.....................no
    PostgreSQL..............no
    TDS.....................no
    DB2.....................no
    SQLite..................plugin (qt)
    SQLite2.................no
    InterBase...............no
```

**Comment by pljones** [comment]
Mine says:
```
QPA Backends:
    GDI.....................yes
    Direct2D................no
```
[config.summary](https://github.com/elieserdejesus/JamTaba/files/1306470/config.summary.txt)

**Comment by elieserdejesus** [comment]
@pljones , your config.summary is showing:
```
PATH=
      D:\qt-5.6.0\qtbase\bin
```

I'm using Qt 5.5.0 here. I tested other versions and the static build fail. Static builds are not tested by Qt team, so it's better just use a "compilable" version. I suggest the 5.5.0. I"m not shure if the Qt version is the real cause of your problems, but it's my best guess at moment.

**Comment by pljones** [comment]
Still no joy.  Same error.
```
D:\Qt\qt-5.5.0-static\plugins>dir /w mediaservice
 Directory of D:\Qt\qt-5.5.0-static\plugins\mediaservice
[.]                        [..]                       dsengine.lib               dsengine.prl
dsengined.lib              dsengined.pdb              dsengined.prl              qtmedia_audioengine.lib
qtmedia_audioengine.prl    qtmedia_audioengined.lib   qtmedia_audioengined.pdb   qtmedia_audioengined.prl
wmfengine.lib              wmfengine.prl              wmfengined.lib             wmfengined.pdb
wmfengined.prl
              15 File(s)     33,736,641 bytes
               2 Dir(s)  163,171,217,408 bytes free
```
The problem is that `dsengined.lib` has external dependencies that aren't available...

Googling for the referenced symbol found [this MS article](https://msdn.microsoft.com/en-us/library/windows/desktop/bb970434(v=vs.85).aspx), which mentions doing `Regsvr32 EvrPresenter.dll` -- but I've no idea where that DLL would live.  It doesn't appear to be under %WINDIR%.

**Comment by elieserdejesus** [comment]
> The problem is that dsengined.lib has external dependencies that aren't available...

Sorry, I have no more ideas or clues. Are you in windows 10 too?

**Comment by pljones** [comment]
I just noticed - you're using a shared build of Qt according to the config you posted.  Is that right?

**Comment by elieserdejesus** [comment]
> I just noticed - you're using a shared build of Qt according to the config you posted. Is that right?

I posted the wrong file. This is the config.summary in the Qt version I'm using to release JamTaba: 
[config.summary.txt](https://github.com/elieserdejesus/JamTaba/files/1309484/config.summary.txt)

**Comment by pljones** [comment]
I've been using `jom` as a build tool.  I see you used `nmake` for configure - did you use it for the full build?  I've been having to rerun `jom` with `/j1` to single-thread it because of build failures -- I may just drop back to `nmake`.  (jom seems to work in Qt Creator okay.)

The other thing I had different was `-shared-runtime` - you don't have it.

Anyway, I'm still getting a build error -- just much shorter:
```
LINK : fatal error LNK1104: cannot open file 'dsengined.lib'
```
... and it looks like that's down to me using `jom`.

I'll clean my build and run it again using `nmake`.  (It takes a day or so...)

**Comment by elieserdejesus** [comment]
@pljones , in QtCreator I'm using jom.
image

**Comment by pljones** [comment]
OK, success!  I ran nmake / VS 2012 builds overnight for Qt 5.5.0 and 5.6.0 -- the build of Jamtaba with 5.5.0 just finished successfully.  (nmake for Qt 5.8.0 with VS 2012 failed.)

**Comment by elieserdejesus** [comment]
> On first run, the VST effect started up and said "Your Jamtaba version is incompatible with previous versions" and appeared to "exit" -- the UI wasn't showing.

You are in a old branch and your VERSION is not updated. I changed the minimum compatible version in last days because the camera is crashing some previous JamTaba versions.
image

**Comment by elieserdejesus** [comment]
Sorry, I closed the PR by mistake.

**Comment by pljones** [comment]
Ah, OK - I'll refetch to my master and rebase this against the latest code.  Thought that might be it - thanks for clearing it up.

**Comment by elieserdejesus** [comment]
> Ah, OK - I'll refetch to my master and rebase this against the latest code. Thought that might be it - thanks for clearing it up.

Thank you for your engagement and patience.

**Pull request closed without merging**
