### PR TITLE
Stereo inversion in local tracks

### PR DESCRIPTION
**Pull request by elieserdejesus**
- [x] Add/create icons for stereo inversion button
- [x] Put the stereo inversion button in local tracks layout
- [x] Disable stereo inversion button if local input is audio and mono.
- [x] Implementing the stereo inversion in audio
- [x] Store/remember the stereo inversion for each local track
- [x] Invert peak meters.

This PR is implementing #377

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@teamikl , @jonjamcam proposed a feature to invert stereo channels in local tracks #377.

I'm working on this feature and a new maintence problem appears. In the last commit I added the button to invert stereo in local track layout:
image

But I have to copy/paste the stylesheet code in Flat.css and Rounded.css to have the button looking ok in both themes. Of course copy/paste stylesheets will be a pain for 2 or more themes. @teamikl , have you some good idea about **how maintain these stylesheets without copy/paste?**

The first and simple idea in my mind is just hard code the common stylesheet in C++ side and the specific theme details in .css files. For example, the icon for stereo inversion button is the same in both themes, so this can be setted in the C++ code. On theme is using rounded borders, this can be writed in .css file. I think is not a 100% elegant solution, but is better than copy/paste :)

**Comment by elieserdejesus** [comment]
@jonjamcam , I finished the stereo inversion feature. Can you help testing the feature?

**Comment by jonjamcam** [comment]
@elieserdejesus Just tested the branch and I find a problem with the "Disabling the stereo inversion if input is mono or no-input" commit (https://github.com/elieserdejesus/JamTaba/pull/379/commits/17ef3abb80914ea59bc62080d44400a9b3ea9add)

I think this should be the case only when there's no VST activated because many vst FX convert a mono input to a stereo output.

**Comment by elieserdejesus** [comment]
@jonjamcam , I removed the "no-input" checking in d0aad91. Now the button is disabled only when the input is mono. The input cat be "no-input" but we can use a stereo VSTi generating a loop, for example, and in this case stereo inversion make sense.

**Comment by elieserdejesus** [comment]
@jonjamcam , I changed the stereo inversion to pre-fader. Pan controls are working correctly right. Can you check this branch again, please?

**Comment by jonjamcam** [comment]
@elieserdejesus It's working OK now.

**Pull request merged**
