### PR TITLE
Public chat

### PR DESCRIPTION
**Pull request by elieserdejesus**
- public chat hosted in heroku (using websockets)

### CODE REVIEW

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , I'm finishing a public chat. 
In this  feature I'm using a new Qt module named websockets. Can you compile this PR in your custom Qt? OR is missing the websockets module?

**Comment by jonjamcam** [comment]
I can't @elieserdejesus 

image

I will have to recompile my qt

**Comment by elieserdejesus** [comment]
@jonjamcam, it's not necessary recompile Qt, I Will write the other way in some minutes

**Comment by elieserdejesus** [comment]
@jonjamcam , is possible compile only the websockets module, it's very fast.

1 - Download **5 - qtwebsockets-opensource-src-5.5.1.zip** from http://download.qt.io/archive/qt/5.5/5.5.1/submodules/

2 - Unzip the downloaded file. I'm not shure if you need unzip in your Qt folder tree, I used this method and works.

3 - Open the file **qtwebsockets.pro** (it's inside your unpacked folder) in your QtCreator.

4 - In QtCreator choose your compilation target kit

5 - The project will be opened in QtCreator. Now choose **release** in bottom left and compile.

6 - Choose **debug** in bottom left and compile again (the debug websockets lib will be compiled).

If you have more Qt Kits you must repeat these steps for each kit.

**Comment by jonjamcam** [comment]
>  it's possible compile only the websockets module

@elieserdejesus It's not compiling in my system :disappointed: . No problem. I have time tonight to recompile my static Qt and see what happens.

**Comment by jonjamcam** [comment]
aaannndddd.... it's working now after recompiling my qt:

image

:+1:

**Comment by elieserdejesus** [comment]
nice @jonjamcam !

**Comment by jonjamcam** [comment]
@elieserdejesus I see some chat messages from public chat/server chat mixed:

image

**Comment by elieserdejesus** [comment]
>  I see some chat messages from public chat/server chat mixed

It's fixed in the last commit @jonjamcam .

**Comment by jonjamcam** [comment]
@elieserdejesus . I found I can invite myself to a jam :thinking: :smile:  . Another things to consider IMO are:

1.- **privacy**: allow the public chat to be turned off (so public chat notifications do not interrupt a jam) and/or user invisible (unavailable).
2.- **filter user**s: I propose the idea of a whitelist (only users in the list will appear in the public chat)

**Comment by elieserdejesus** [comment]
>  I found I can invite myself to a jam 🤔 😄 .

Yes @jonjamcam , It's just to test purpouses. I will fix the "invite myself" feature before finish this PR.

**About the 2 proposed ideas:** Please create 2 issues, I will work in these ideas in the next release.

**Pull request merged**
