### PR TITLE
Configurator

### PR DESCRIPTION
**Pull request by Ezeer**
AH AH AH AH ! YOUR NIGHTMARE ELIESER !!
lol 

So now let's simulate my stuff is boring , a big piece of shit , you know it's a crime to merge that ,
but you don't want to hurt me .

I am curious to see how you will react to that  .
uh uhuh ....

### CODE REVIEW

**Comment by elieserdejesus** [comment]
I think some of these commits are merged. I don't know what happens if we merge merged commits. 
Maybe a stackoverflow in github servers? :)

**Comment by Ezeer** [comment]
ah ah ah ah ... 
That's were i'm waiting @teamikl  .
Perhaps he already knows ?

**Comment by Ezeer** [comment]
@teamikl  lol ! team iki = https://en.wikipedia.org/wiki/Iki_(aesthetics) 
very good ! ;)

**Comment by teamikl** [comment]
Hi, I don't know what you worry ?
there is no conflict as this shows Merging can be performed automatically.

If you care commit log history,
then edit by git rebase or reconstruct new clean branch by cherry-pick.
if you want use your merge tools then the "command line instructions show" will help u.

**Comment by Ezeer** [comment]
@elieserdejesus  Remember it is just a simulation here . You don't have to decide if merge or not , perhaps just try to close it when our chat will be over . It is just a kind of training .
:)

**Comment by Ezeer** [comment]
That feature is cool in PR : all commits are displayed since i opened it !
So it is a strategical place to discuss about commits .....
I like that .

**Comment by teamikl** [comment]
This moment, I am not trying to build it, just review by reading code.

- I saw mixing indent styles for "foreach" and not brackets for "if/else"
   Is there coding guide line which project code ?
  and static code check like Lint, and auto formatting tools?
  if you had one, we can share the config in repo.


- PresetInputChannels naming that method with upper letter has something special mean?
  look like a class name. and noun is like a property name.

- access to the internal (PresetInputChannels)
  Is it just a public alias for accessing private method ?
  C++ has "friend" keyword for that.

  Or the private method can be public? if situation allow its simple way
  which can drop the wrapper for modified access level.

  There are several choices for solution, but they are often tricky.
  I do not know current context well, so I am not sure which approach is
  suitable. current approach is also ok (wrap private) easy to understand.


- How will you get the preset name on_LoadPresetClicked? via QObject::sender() ?
  Instead of connect to the slot directly, QSignalMapper can handles this.

**Comment by Ezeer** [comment]
+ **I saw mixing indent styles for "foreach" and not brackets for "if/else"
Is there coding guide line which project code ?
and static code check like Lint, and auto formatting tools?
if you had one, we can share the config in repo.**

If you see : 
if(...){
}
it's elieser's code .

when if(...)
         {
         }
it's me . ( i can't read easily the elieser's formatting )
^^

+ **_ PresetInputChannels naming that method with upper letter has something special mean?
look like a class name. and noun is like a property name.**
it should be presetInputChannels() ( elieser is doing like that )

+ **access to the internal (PresetInputChannels)
  Is it just a public alias for accessing private method ?**
 Just an alias .
 SHow me please how to use a friend here . ( ^^ )
 *current approach is also ok (wrap private) easy to understand.*
 thx , i was searching a quick working solution , but if you got a better design we'll adopt it .
 ( but please try to keep the things simple while we try to connect things .... )

 + **How will you get the preset name on_LoadPresetClicked? via QObject::sender() ?
    Instead of connect to the slot directly, QSignalMapper can handle them.**
   Give me an exemple if you can , i don't have worked on that yet .

   Feel free to work on that if you are inspired .
  Thank you for your help !

**Comment by teamikl** [comment]
Let's me test coding in markdown

```cpp
if (cond) {
    do_something();
}
```

```cpp
if (cond)
{
    do_something();
}
```

well, those brackets are both ok.
----

I know everyone have different experience.
so any style is ok but mixing them is not good idea.
auto formatting tool may help this task, or your IDE has the style support?

- following elieser's style. since the most code he written.
- qt's official style is another choice, because u will read a lot qt's code
  they are documented.

This is quick search results about coding style / qt project.

- https://wiki.qt.io/Qt_Coding_Style
- https://wiki.qt.io/Coding_Conventions
- https://doc-snapshots.qt.io/qtcreator-extending/coding-style.html

```

**Comment by teamikl** [comment]
This is a minimum example of using "friend".

http://ideone.com/Fa6JLL

note, the friend class can access to all private which
there is friend function but it's no instance method.

there are also discussions,
the most of time when needed "friend", its time to re think
the reusability of codes by design classes.
For now the quick solution you already done is ok. it's not much important how do it at all.

design can be another topic, private is keep they are private.
the common routine could be separate to somewhere accessible from both classes.

**Comment by teamikl** [comment]
Wait, no spaces after keyword ?

I have another experience too.
I used to work with were

MACRO(...) function(...)   and   if (...) {

**Comment by teamikl** [comment]
@Ezeer 

Here is the sample code compares QSignalMapper and QAction::setData/sender()
https://gist.github.com/teamikl/f77dbb3bfa676bc4ce81

**Comment by teamikl** [comment]
# Coding style

## Indents

some indents were strange to me, is it mixing tab character on browser?
I saw were:

```cpp
if (condition)
{do_something();

}
```

```cpp
if (condition)
    do_something();
    else
    do_nothing();
```

## Brackets

Style effects to coding productivity.
e.g. when some one want to comment out the do_something() line,
brackets can keep the valid syntax. no much edits.

```cpp
if (condition) {
    // do_something();
}
else {
    do_nothing();
}
```

on this view point, an acceptable case if-statement one line.
when the body is simple enough and no else-clause.
```cpp
if (condition) do_something();
```

## solutions

auto formatting tool or set coding style support on IDE?

**Comment by teamikl** [comment]
I have an opinion about slot naming.

In Qt signal/slot,  slot naming can be action name,
no need to describe what kind event is that. it's signal's naming.

> connect(sender, SIGNAL(event name), receiver, SLOT(action name))

This is a different point, slot is not event handler.
slot is callable as general instance method.


Qt has event system too, their naming are like xxxEvent()
it's used by overriding and event object is passed as argument.

- [Events and Filters](http://doc.qt.io/qt-5/eventsandfilters.html)
- [Signals and Slots](http://doc.qt.io/qt-5/signalsandslots.html)

**Comment by teamikl** [comment]
https://gist.github.com/teamikl/f77dbb3bfa676bc4ce81/revisions

this is an example, remove receiver slots
signal can connect to controller's slot directly.

**Comment by Ezeer** [comment]
Thank you for the documentation and your ideas .
I will study that with care .
One thing i already know is that i can't work with Qt style of coding on that : 
// Wrong
 if (codec)
 {
 }
 else
 {
 }
 
 // Correct <<< THEY SAY ....
 if (codec) {
 } else {
 }

I like to have space around me , it's same with the words .
Feelings ...https://www.youtube.com/watch?v=VmO_0tIGo-4

**Comment by Ezeer** [comment]
That could mean i make something that works but not following project rules , someone take it and
make it better . Elieser did that for example with the singleton for the Configurator class .
So Tea you could apply your ideas on my code later , for me that is not a problem but a solution .
:)

**Comment by Ezeer** [comment]
Hey , just checked that  tea : 
https://gist.github.com/teamikl/f77dbb3bfa676bc4ce81/revisions

not finished to read it , how can i use a revision please ?

**Comment by teamikl** [comment]
I saw now This branch has **conflicts that must be resolved** now.

this thread was the PR simulation, so
I can explain the work flow information. this is about work on branch model.


In this case, master repo update often, so branch may have often conflicts.
no need to solve the conflict soon, you can delay it until merge to master time.
work only the branch topic, forget another extra tasks, do not need to do now.

However, there are several strategies to avoid conflicts.

## Implement new feature as separate module

  this is up to the situation though, if possible. Instead of start hard coding,
  create a new file then write a code there that will not have conflict,
  master repo does not know the new files you created on the branch.

  In the first stage, you can put everything into the file.
  you can move the codes later, just leave comment like

> // FIXME: this code will move to main controller later
 
if you use IDE, they will shows those tagged comment in TODO list.
or programmer editor has such feature as plugins.
in the final stage when implement the topic feature is finished then
ready to go merge into mater, you can do these refactorying tasks.

 you can remove the new files you created if no need in master repo anymore.
 working on separate files they can be just temporary for avoid conflict.

 implement a feature as module has another merit,
 if they are independent, then easy to write a test.

**Comment by Ezeer** [comment]
" In the first stage, you can put everything into the file.
you can move the codes later, just leave comment like

// FIXME: this code will move to main controller later
if you use IDE, they will shows those tagged comment in TODO list.
or programmer editor has such feature as plugins.
in the final stage when implement the topic feature is finished then
ready to go merge into mater, you can do these refactorying tasks."

very interesting ... i'll try that , thank you teamiki .
Now i will try to fix the merge problem ...

**Comment by elieserdejesus** [comment]
Thanks Ezee!

**Pull request closed without merging**
