### PR TITLE
[WIP] correcting "founded" string

### PR DESCRIPTION
**Pull request by jonjamcam**

### CODE REVIEW

**Comment by elieserdejesus** [comment]
Thanks 😄

**Comment by jonjamcam** [comment]
I guess all translations need this fix @elieserdejesus

**Comment by elieserdejesus** [comment]
> I guess all translations need this fix @elieserdejesus

It's true @jonjamcam , is possible use the **Edit -> Find/Replace -> Advanced Find ** in QtCreator to search for all **founded** ocurrences in *.ts files and replace with the correct word.

**Comment by jonjamcam** [comment]
I'll replace them shortly. no problem

**Pull request merged**
