### PR TITLE
[WIP] Fire theme

### PR DESCRIPTION
**Pull request by jonjamcam**

### CODE REVIEW

**Comment by jonjamcam** [comment]
new changes:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , It's working. I can see a difference between ninbot:2051 and ninjamer:2051. 
Ninjamer:2051 is not too hot, I prefer these colors (ninjamer:2051).

**Comment by jonjamcam** [comment]
> I can see a difference between ninbot:2051 and ninjamer:2051. 

The code the same for both. I used a color trick found by pure chance while making the Black Theme (https://github.com/elieserdejesus/JamTaba/issues/396#issuecomment-221999529). Probably because there's no apparent division between the content color and the panel color it appears different. I'll try to get as close as **ninjamer** color as possible for a full server.

**Comment by jonjamcam** [comment]
Trying to get closer to the palette:

image

@elieserdejesus what do you think?

I tried black background, but it didn't look good so far. Maybe the black and blue have to go in the borders or elsewhere.

**Comment by elieserdejesus** [comment]
@jonjamcam , I prefer the 2nd picture.

I noticed the black border in the user name field, and is looking very good. I think you can explore the black border in public rooms widget too.

Another suggestion: This initial window contain 3 main blocks/parts: the local tracks (left side), public rooms (center) and the master section (bottom). At moment these 3 sections are using very similar palletes. Is important use different palletes in each section (specially in backgrounds) to visually communicate the 3 main sections in the GUI. If this communication fail users will see just a bunch of rectangles/blocks.

**Comment by jonjamcam** [comment]
> I prefer the 2nd picture.

pushed on https://github.com/elieserdejesus/JamTaba/pull/489/commits/84d04465fbc1896d08edc47c9a4a54cfa4ae1843.

**Comment by jonjamcam** [comment]
@elieserdejesus I made some adjustments to the palette. Please tell me if you think this is the right direction to go:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , the general result is getting very interesting, but in my eyes the middle zone (public rooms) is too "hot". 
I like the background color in the bottom "zone" (master section), it's perfect in my opinion. But the middle (public rooms) is a bit confuse in my eyes, too much visual stimulus with red tones. 

I'm not shure how to solve the "too hot" visual, but the 2 initial ideas in my mind are:
1 - use a more darker/soft/smooth color in public rooms background
2 - change the red tone in the screen background to a brighter color. Maybe a very soft yellow tone.

**Comment by jonjamcam** [comment]
> in my eyes the middle zone (public rooms) is too "hot". 

then let's use the old color for this:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , I think the constrast between the main background colors and the other elements (buttons) is not enough. If you look at the 3 backgrounds in the next image is clear all "tones"  are in the same direction (too hot):
image

I think a possible solution is play with lighter colors in main section backgrounds. I tried some other possibilites, just to show the effect of a lighter background:
image

**Comment by jonjamcam** [comment]
> I think a possible solution is play with lighter colors in main section backgrounds

@elieserdejesus OK. I understand now why you dropped the Orange in the first place :D. This colors are slippery to say the least. I have to admit I'm a bit lost with regards to direction.

 In order to keep the mind sane I normally choose the palette in the first place and then try to stick with it. I propose to pick up the primary colors to use first.

So in summary these palettes were not working as expected:

1.- Volcano:





***
2.- Fire:











***

 I have another ideas:

3.- This palette could be a good reference, although getting away from orange-fire into a more reddish-yellow tone:

image

 The colors may be a bit dark, though.

4.- This is a red-white palette used in a rebirth MOD:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , I have a last idea to use "Volcano" pallete:
image

We can see the most hot tones (red and orange) are used as background colors only in the top (menu) and in the top section of main background. No text elements (except the menu items) are placed directly in top of this "hard" red/orange background. The interactive elements (buttons, knobs) are placed in top of more smooth (not too hot) colors, so is more easy get good contrasts.

**Comment by elieserdejesus** [comment]
@jonjamcam , I started a "Volcano" theme, totally inspired (read copy and paste :D) in the Volcano plugin.   I used the "fire" tones in main background and played with almost transparent backgrounds in the other sections. I think the result is interesting. Are you interested in continue this theme?

**Volcano theme**
image

**Comment by jonjamcam** [comment]
looks good! and FAST. Ok. I can keep the idea and finish it, np.

**Comment by jonjamcam** [comment]
Fire theme is dropped. Working on Volcano Theme instead https://github.com/elieserdejesus/JamTaba/pull/507

**Pull request closed without merging**
