### PR TITLE
Fixing chat collapsed fix #985

### LINKED ISSUE #985: chat window collapsed always when joining a server after lanching Jamtaba
The problem I see here is the "remember" option is not working if you want the chat to be always shown

### PR DESCRIPTION
**Pull request by elieserdejesus**
@jonjamcam , this PR is fixing the issue #985

Can you test, please?

### CODE REVIEW

**Comment by jonjamcam** [comment]
> this PR is fixing the issue #985

Can you test, please?

not solved yet in my system. This is what I do to reproduce:

1.- launch Jamtaba (tested in standalone)
2.- connect to a server.

Chat is collapsed by default at this point

3.- click chat tab to uncollapse
4.- exit server
5.- exit Jamtaba
6.- relaunch Jamtaba
7.- enter a server

chat is collapsed

**Comment by elieserdejesus** [comment]
@jonjamcam , I tested your steps here and is working. 

I have 2 ideas:

1 - Ensure you are compiling all the changes: check if you are in the correct branch and you have the last commit pulled. Run **clean** in QtCreator and run a full compilation.

2 - Delete your json config file to see if the problems is some old value.

**Comment by jonjamcam** [comment]
>  I tested your steps here and is working

Yes @elieserdejesus It's working now after deleting the json file.

**Comment by elieserdejesus** [comment]
I tested the version migration to check if the previous json file was conflicting with the new version. 
Works fine here.

**Comment by jonjamcam** [comment]
@elieserdejesus Sometimes the chat setting changes to true if you exit jamtaba from the main window:

image

I guess it's saving main window's "collapsed state" that can't be changed. is it only me?

**Comment by elieserdejesus** [comment]
Same problem here @jonjamcam , fixed in https://github.com/elieserdejesus/JamTaba/commit/9263885c8bdbb47b7d315ad17335cd3812f1a5a0

**Pull request merged**
