### PR TITLE
i10n translate message resources

### PR DESCRIPTION
**Pull request by teamikl**
Hello!
Yesterday, I was asked about translation menu for JamTaba.
I put this temporary work as WIP

Here is the start point: [Qt Documentation - Internationalization with Qt](http://doc.qt.io/qt-5/internationalization.html)

## Tasks

- [x] I had tried to start Japanese translation as sample
- [x] added install translator code to app main
       this is Static translation, set translator only application run-time.
- [x] added more tr() mark for plain string literals
       some resources are moved the context.
       Because translation need to call tr() runtime, can't be global scope.
- [x] modified string construct ways  from "+" operator to QString.arg()
       Because, some language grammar may have different order of terms.
       see: [Using numbered arguments](http://doc.qt.io/qt-5/i18n-source-translation.html#using-numbered-arguments)
- [x] detect locale and load translation resource at application run-time
- [x] load translation resource from disk (for debug use, user can override embed resource)

## Discussions

- [x] which project file (.pro) should have the TRANSLATIONS? sub or root project
- [x] where to manage translation files (*.ts)  ~~now its under PROJECT temporary~~. it's not correct path
- [x] and compiled resource (*.qm)   resource compiler can embed them?
- [x] write tutorial/workflow for translator to contribute translation ~~(maybe wiki page)~~
  - *.ts file is xml file, it's human readable/editable format. but risk manual edit can break the format.
  - Qt Linguist is an optional tool
  - NOTE: Qt Linguist standalone was on qt apps site, but old version.
  non-developer translation contributor also need to install Qt~~Creator~~. if they want use Qt Linguist

## This PR will NOT

Just not in this PR, I think that should be separate issue.

### switch translation resource dynamically

  switch resources dynamically like Jamtaba v1, requires more works
  [Qt documentation Dynamic Translation](http://doc.qt.io/qt-5/internationalization.html#dynamic-translation)

the implementation costs, widget classes have to override the language change event for the refresh.

### Translate Jamtaba sites / ChangeLog etc

This is a related topic but another issue. for Japanese ChangeLog translation
I had https://bit.ly/JamTabaChangeLogJa  that generate from google spreadsheet.

### CODE REVIEW

**Comment by teamikl** [comment]
>  where to manage translation files (*.ts) ~~now its under PROJECT temporary.~~ it's not correct path
    and compiled resource (*.qm) resource compiler can embed them?

now it's changed
* changed project layout for translation resources
  * ./translations/ for *.ts files
  * ./src/resources/tr for *.qm files

### Setup new translation languages:
1. add .ts file entry into translations.pri
2. add .qm resource entry into ./src/resources/jamtaba.qrc
   with alias and lang attributes

### Update translation:
1. lupdate PROJECT/Jamtaba.pro
2. Linguist .ts file
3. Release then move the generated .qm file into ./src/resources/tr

### TODO
- [ ]  fallback for unknown locales,
      now it assumes Japanese locale to launch.
      application may not start on another locale environment.

**Comment by elieserdejesus** [comment]
Nice work @teamikl.

About the discussion **which project file (.pro) should have the TRANSLATIONS? sub or root project**:
2 subprojects need the translations resources, these projects are **VstPlugin.pro** and **Standalone.pro**. Putting the translation files in the main project **Jamtaba.pro** we will avoid duplicate the translation stuff in the subprojects, but you are forced to compile the entire stuff just to check a change in the translation (very annoying).

**Comment by teamikl** [comment]
> forced to compile the entire stuff just to check a change in the translation 

Qt Linguist tool supports validation and preview for .ui and .cpp resources.
for .ui that will show GUI preview, for .cpp show the source code.

Currently there are no tasks to compile translation resource in .pro file.
that requires manual task to release .ts to .qm and move the .qm into resource path.
(this workflow should be automated by script in future)

for the check a change in the translation,
I will try to add load the translation resource from disk.
no embed resource, then not require compile. this is just for the check.


## 1 root project

- Jamtaba.pro

all resources into one resource,
this mean Standalone contain VstPlugin resources, and vice versa.
file size is not problem (1 qm file is now about <20kB) but not good module design.

if other project want to use Jamtaba-common, resource contains unnecessary stuffs.
but this was simple and easy solution.

## 2 sub-projects

- VstPlugin.pro
- Standalone.pro

both include Jamtaba-common.pri, if each project has own translation resources.
Problem is translate contributors have to do the duplicate work.

to avoid the duplicate then Jamtaba-common resource also should be separated.

## 3 sub-projects

- VstPlugin.pro
- Standalone.pro
- Jamtaba-common.pro (separate the common part as project)

This looks clean design, but each project has own resources then
three resource files is maintenance cost for translation contributors.


----
BTW, this issue topic was L10N (Localization)  ... not I18N (Internationalization)

**Comment by teamikl** [comment]
update initial comment, add new task item
```markdown
- [ ]  load translation resource from disk (for debug use, user can override embed resource)
```

**Comment by elieserdejesus** [comment]
Tea, I think create a new .pro file for translation stuff is too much at moment. Let's consider the simple options first. In standalone we have some string messages related with audio and midi stuff, and these messsages are not used in vst plugin (audio and midi are handled by the host). If I remember correctly all other messages/strings are shared between standalone and vst plugin, so we can try put all translation stuff in the common.pri at moment. I never work with Qt Linguist, maybe we can use some prefix in messages "names" to have standalone specific messages?
```
standalone.audioFailMessage = "Critical audio error!"
```

I suppose is more easy for translators open one file containing the messages to standalone and vst plugin. But I'm not shure about all this stuff, I'm just a big Zero in Qt translation world :)

**Comment by teamikl** [comment]
> create a new .pro file for translation stuff is too much

I think so too.

>I suppose is more easy for translators open one file containing the messages to standalone and vst plugin.

:+1:

the easiest solution was add the "TRANSLATIONS" to root project.
now this branch implemented that way.

the translation source supports context, no worry about namespace/prefix.



- [ ] ./translations can be root directory? or should be ./src/translations?
- [ ] *.qm file is a binary file, can be in repo? or should be out of repo?
      users can generate them from *.ts file by lrelease.exe command.
      If generate these by user build time then I will research this more details,
      this question back to the topic which .pro should have the "TRANSLATIONS".


my proposal is:

- ./translations root directory where contributors easy to find
- make ./translations/README.md describe how to add translation resource
- ./translations/*.ts   xml text file which Qt Linguist open and edit
- ./translations/*.qm  binary resource which generated by Qt Linguist  "release" operation. (or lrelease command)

if those *.ts and *.qm files were in same directory then no need move the generated qm file.
All files into the same directory at this moment, there are no many files yet.

**Comment by jonjamcam** [comment]
> non-developer translation contributor also need to install QtCreator. if they want use Qt Linguist.

Qt Linguist looks very easy yo use, but I think installing QTCreator additionally is a drawback for the average Joe. I'm thinking specifically about Magnus and Doublebass.

**Comment by teamikl** [comment]
@jonjamcam 

sorry, I had said wrong info,
that was not part of QtCreator, it's Qt development environment's.

I was looking for online translation support site,
some of them provide editing Qt's TS file on browser, but the interface were not so useful. 
(may be they are good for collaboration use case)

I will mention how to make the translation without Qt Linguist
TS file is XML file, plane text editor (which support UTF-8 encoding) also can do this task.

otherwise, there is another task require Qt development environment,
that is "lupdate.exe" program to generate and update .ts file...

- [ ] make a workflow easy to contribute translation resource for non-developer.

**Comment by elieserdejesus** [comment]
Tea, I totally agree with  put **translations** in root folder.

**Comment by teamikl** [comment]
Added guide document for translate resource contributions
https://github.com/teamikl/JamTaba/blob/i18n-resources/translations/README.md

I need review, @jonjamcam can you try following this guide and make your translation?

If @elieserdejesus does not mind *.qm (binary file) into repo,
then now status ok to be merged. I will remove [WIP]

There are several rest topics, if users does not want to use locale or select another locale for debug.
and also how to contribute guide for non-developers. they can be another chances.

**Comment by teamikl** [comment]
Just info about Qt Linguist

I had worried about duplicate works for Jamtaba-common's resource
Qt Linguist could manage the situation. [Reusing Translations](http://doc.qt.io/qt-5/linguist-translators.html#reusing-translations)

This is an advanced use, and require all translators to use Qt Linguist.

**Comment by elieserdejesus** [comment]
Nice @teamikl , I have no problems with the .qm file in the repo, it's for a good cause :)
Just for check, can I integrate your PR?

**Comment by teamikl** [comment]
@elieserdejesus 
sure Ok. it's not reviewed enough tho, I think others can't test yet.
the translation work for ja_JP locale only now.
If there was missing something, let's continue this topic in another issue.

Finally, we need to share knowledge about the translation process in Qt5 app.
Summary:

- for coders
  - [Writing Source Code for Translation](http://doc.qt.io/qt-5/i18n-source-translation.html)
    - use tr() for all user visible text, it's mark for translate
      - internal text like property/object name, no need
    - use .arg() with numbered arguments to construct string
  - [Qt Linguist Manual: Developers](http://doc.qt.io/qt-5/linguist-programmers.html)
- for translators
  - [Qt Linguist Manual: Release Manager](http://doc.qt.io/qt-5/linguist-manager.html)

**Comment by jonjamcam** [comment]
> can you try following this guide and make your translation?

Sure @teamikl . I think we need the PR merged to access translations.pri?

**Comment by teamikl** [comment]
@jonjamcam 

>  I think we need the PR merged to access translations.pri?

Yes, you can wait the PR merge or you could checkout my teamikl:i18n-resources branch.

**Comment by teamikl** [comment]
@elieserdejesus 
There is an additional task for release manager.

TS File contains filename / lineno info, need to update
*.ts and *.qm files should be update before release.

```
# update *.ts files
lupdate PROJECTS/Jamtaba.pro
# generate *.qm files
lrelease PROJECTS/Jamtaba.pro
```
no need to worry about missing translation, English is used as fallback.

Translators can do the translation task during release coordinate.

**Comment by elieserdejesus** [comment]
@jonjamcam  and @teamikl , this pull request is integrated in master. Thanks for the nice job!

**Comment by jonjamcam** [comment]
@teamikl One question. I the guide you posted before (https://github.com/teamikl/JamTaba/blob/i18n-resources/translations/README.md) says to use the format:

TRANSLATIONS + $PWD/(locale).ts 

to translations/translations.pri. Why does it differ from the existing line:

translationspri

**Comment by elieserdejesus** [comment]
@teamikl , in my machine Jamtaba is starting translated to Japanese. The symbols are beautifull, but I can't read anything, hehe.

Just to test I separated the translator install condition in main.cpp
```
    bool a = translator.load(QLocale::system().name());
    bool b = translator.load(":/messages");
    if (a || b) {
        application->installTranslator(&translator);
    }

```
**a** is always false here, and **b** is always true. 
Any ideas?

**Comment by jonjamcam** [comment]
First the lupdate command send an error:

lupdate

I changed the syntax to

TRANSLATIONS + $PWD/(locale).ts

and now it seems to work:

lupdate2

translations_dir

**Comment by teamikl** [comment]
@jonjamcam 

sorry, it was typo  "+" -> "+=" in README
please follow actual file code I wrote for ja_JP

@elieserdejesus 

the messages.qm was alias
```
  <file alias="messages.qm" lang="ja_JP">../../translations/ja_JP.qm</file>
```

maybe resource should have ./tr/(lang).qm
I did not check fallback for lang="(locale)" attribute in resource.

```
  <qtresource prefix="/tr">
    <file alias="ja_JP.pm" lang="ja_JP">../../translations/ja_JP.qm</file>
```

```
    QString localeName = QLocale::system().name():  // e.g. "ja_JP"
    bool a = translator.load(locale);  // ja_JP.qm file ... it's for debug use, no need re-compile exe
    bool b = translator.load(":/tr/" + localeName);  //   :/tr/ja_JP.qm in resource
```

**Comment by elieserdejesus** [comment]
@teamikl , I commit the fix using your ideas, it's working now.

**Comment by jonjamcam** [comment]
did a recent pull but I may have a compile problem with minGW x86 (should I make a separate issue?):

compile error2

**Comment by teamikl** [comment]
@elieserdejesus 

thanks
./translations/README.md also should follow the change

Can you do that update ?
I also had add the code for test the change.
If i made PR from this branch then will have merge conflict.

@jonjamcam 

the "alias" was from this PR
the latest HEAD repo does not have. can you try again ? may be its fixed

**Comment by teamikl** [comment]
@jonjamcam 

I did not read the error report carefully.
the duplicate alias was this issue related, but it was warnings.
I am not sure about errors below.

**Comment by teamikl** [comment]
@jonjamcam 
Can you push the working branch to remote (github) ? I can try test.

**Comment by jonjamcam** [comment]
@teamikl when I push it's directed to elieser's origin, not to my  fork.

**Comment by elieserdejesus** [comment]
@jonjamcam , try click with right mouse button in project name and run these 3 actions:
1 - clean. 
2 - Run qmake
3 - rebuild

**Comment by elieserdejesus** [comment]
@teamikl , the translations README file is updated, very nice work, thanks! I will follow your instructions soon to translate for portuguese.

**Comment by jonjamcam** [comment]
THX. Working now. JAmtaba in spanish!

**Comment by elieserdejesus** [comment]
@jonjamcam , this picture put a big smile in my face, this is really nice. Thanks for you and @teamikl !

**Comment by jonjamcam** [comment]
It is! @teamikl this is great! and it did it automatically.

**Comment by teamikl** [comment]
@jonjamcam 
nice!  next, you can make the PR =)

@elieserdejesus 
you're welcome

I have a question
es_BR and es_CL are same language ?

Locale is (language code)_(country code)
if they can be same resource then there was another solution
 use lang="es" attribute in qtresource, instead of locale file name.

file name require exact matching, locale can detect more flexible by language and country.
if we meet the situation, the resource look up mechanism can change to use locale.

**Comment by elieserdejesus** [comment]
@teamikl , your question is very common. Spanish and Portuguese are very similar, but not the same language. My locale is **pt_BR** (portuguese, Brazil).

**Comment by jonjamcam** [comment]
> you can make the PR =)

@teamikl I will as soon as I figure out how to point my local folder to my fork. Anyway I have another separate "fork" folder, so I can do it there again if i get crazy...:D

**Pull request closed without merging**
