### PR TITLE
All themes looper button non xmit color fix 

### PR DESCRIPTION
**Pull request by jonjamcam**
- [x] Rounded theme looper button fix

- [x] Black theme looper button fix

- [x] ice theme looper button fix

- [x] Flat theme looper button fix

- [x] Volcano theme looper button fix

- [x] Rounded theme looper button icon color fix

- [x] Boost button non-xmit unchecked color fix

### CODE REVIEW

**Comment by jonjamcam** [comment]
@elieserdejesus I had a little issue with the **rounded** theme and the looper button **disabled** in **non-xmit** state. The problem seems to be that the circle inside the icon has the same color of the button so it disappears when dimmed:

image

I noticed that the looper icon has sligtly brighter color than the stereo inverse button for example. What do you think is a better solution:

1.- change the "non-xmit" colors for this particular theme.
2.- match the looper icon to be a little darker

**Comment by elieserdejesus** [comment]
>  I fixed the easy way. Changing the background color for that specific button:

Nice @jonjamcam . Can I merge the PR?

**Comment by jonjamcam** [comment]
> Can I merge the PR?

Sure. It's complete.

**Comment by elieserdejesus** [comment]
thanks!

**Pull request merged**
