### PR TITLE
Voice chat

### PR DESCRIPTION
**Pull request by elieserdejesus**
- Receiving voice chat
- Transmiting voice chat audio

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , can you help testint this PR?

- The remote tracks will show a small microphone icon when receiving voice chat audio
- You will see a new button in local tracks to activate the voice chat mode. In voice chat mode the audio is always encoded in the lowest quality.

The colors of this voice chat button are not good. Can you improve these css files?

**Comment by jonjamcam** [comment]
working fine:

1.- reaninjam -> jamtaba OK as expected
2.- jamtaba    -> reaninjam OK as expected
3.- previous jamtaba receives audio as expected (voice chat received as normal ninjam)
4.- tested wahjam too. in my system same as previous jamtaba

did a test in cockos private server over the internet using large bpi/bpm (64bpi/40bpm)

**Comment by elieserdejesus** [comment]
Thanks for the test @jonjamcam .

I will add your suggestions.

> 3.- Persistence: Button settings are not stored for future use.

> As video uses the second channel, I think voice chat mode should be disabled if video is used.

yep, I'm doing this.


>  I'm compiling using win7 x64 and static qt 5.5.1

Have you the qt 5.5.1 source? They dropped this version from qt archives.

**Comment by jonjamcam** [comment]
> Have you the qt 5.5.1 source

I was very hard to find indeed, but they still exist somewhere on the net.

**Comment by elieserdejesus** [comment]
> @elieserdejesus. Just finished the buttons for all themes as a first take. Should I PR later after merge?

Yes @jonjamcam , I will merge this PR right now and you can put your changes as a new PR. Thanks man!!!!

**Comment by jonjamcam** [comment]
@elieserdejesus I still don't feel comfortable with the location of the voice chat button. If I may 
 suggest an alternate location. donno if it's possible:

image

I did reduced it about 20%

**Comment by jonjamcam** [comment]
did it @elieserdejesus :


image

what do you think?

**Comment by elieserdejesus** [comment]
nice @jonjamcam , thanks!

**Pull request merged**
