### PR TITLE
[WIP] Receiving and transmiting video streams

### PR DESCRIPTION
**Pull request by elieserdejesus**

### CODE REVIEW

**Comment by jonjamcam** [comment]
Nice we can test the new video feature @elieserdejesus . I just tried to compile this one using mingw32, but I have an error:

image

my QT version is two years old!:

image

Do you think I need to update?

**Comment by elieserdejesus** [comment]
Hi @jonjamcam , I'm using **Qt 5.5.0** here, your version is ok.

The problem in your picture is in **Unknown modules multimediawidgets multimedia**.

These Qt modules are used to capture and show the camera frames. Check if your Qt contain these files in the picture above (your file extensions will be different because I'm using the msvc version, not the MingW version, but the file names are similar):
image

If you not have these files (this is my first guess) you need a "more complete QT", including these multimedia modules. 

You compiled Qt yourself or are you using a official release?

**Comment by jonjamcam** [comment]
> If you not have these files (this is my first guess) you need a "more complete QT", including these multimedia modules.

Looks that's the problem. I don't have the libs.

> You compiled Qt yourself or are you using a official release?

yes, Maybe I'll have to compile it again or add the libs manually.

**Comment by elieserdejesus** [comment]
@jonjamcam , these dll files will work fine for JTBA standalone. But I suppose these DLLs are from a official Qt release, not from your custom Qt build.  In this case you must register this official Qt release in your QtCreator to compile JTBA using this Qt version. 

QtCreator can work with various Qt flavors, and you can choose the "Qt flavor" before compile. Here I'm using 3 Qts: **msvc 32 bits**, **msvc 64 bits** and sometimes **mingw** (just for compatibility tests).

image

**Comment by jonjamcam** [comment]
@elieserdejesus  I'm getting closer, can build now, but one compiler error:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , now the FFMpeg libs are missing. Please download and unpack the libs again (I added the ffmpeg libs):

[https://www.dropbox.com/s/qckwsmaqlditwpb/JamTaba-static-libs.zip?dl=0](https://www.dropbox.com/s/qckwsmaqlditwpb/JamTaba-static-libs.zip?dl=0)

If the download not contain the ffmpeg libs please wait some minutes and try download again, my connection upload (dropbox) is slow.

**Comment by jonjamcam** [comment]
@elieserdejesus I just downloaded the libs, but it looks like the FFMpeg libs are still missing:

image

Exactly the same size than the previous file

**Comment by elieserdejesus** [comment]
My bad @jonjamcam , the upload is finished now. Can you try again?

**Comment by jonjamcam** [comment]
@elieserdejesus It's compiling now, only one error

image

**Comment by elieserdejesus** [comment]
@jonjamcam , I added a commit fixing this error in mingw. Please try again after a **git pull** in this branch.

**Comment by jonjamcam** [comment]
still on error @elieserdejesus 

image

**Comment by elieserdejesus** [comment]
@jonjamcam , I re-installed Qt-mingw here, fixed some errors, etc. But a new error appear and searching for the solution I discover it's a incompatibility between ffmpeg and mingw. 

I think the better approach at moment is drop mingw, keep just the msvc.

Can you try to instal msvc (Visual Studio **2013** community)? It's free, can compile 32 and 64 bits and you will be able to compile the VST plugin too.

The current version is 2017, but I recomend the **2013** version, just to avoid version related errors. 
You can see the instructions to download Visual Studio 2013 [here](https://social.technet.microsoft.com/wiki/contents/articles/38006.visual-studio-how-to-download-older-versions.aspx)

**Comment by jonjamcam** [comment]
> Can you try to instal msvc (Visual Studio 2013 community)? It's free, can compile 32 and 64 bits and you will be able to compile the VST plugin too.

Sure @elieserdejesus . That sounds good to me. I'll give it a try. thanks.

**Comment by elieserdejesus** [comment]
@jonjamcam , I fixed a related bug some minutes ago. The bug appears every time I turn off and turn on the camera again. I will build a new pre release including this fix.

@jonjamcam , can you help with some test cases? If yes, I have some cases in mind:

- [ ] JamTaba to another JamTaba - check the audio transmission while xmiting video
- [ ] JamTaba to ReaNinjam -  xmit audio and video to **ReaNinjam** and check if it's ok. ReaNinjam will just drop the video interval because is not tagged (OGGv) as a valid ogg vorbis data. 
- [ ] JamTaba to an older JamTaba - last JTBA release can receive the new video intervals data and just drop the received material, without crash?

**Comment by jonjamcam** [comment]
> , can you help with some test cases?

I'm on it @elieserdejesus . I can test OK with prereleases

**Comment by jonjamcam** [comment]
First observation:

Jamtaba standalone 2.0.21 in one computer and Jamtaba standalone 2.0.20 in another computer using ninbot server. I get a crash after the "preparing" stage ends in jamtaba 2.0.20 when video is used. No crash in jamtaba 2.0.21 and no crash if camera is turned off

**Comment by elieserdejesus** [comment]
Thanks for the tests @jonjamcam .

> JTB beta makes old jamtaba clients crash too as soon as video is received

This can be a problem. Right now I can see just one solution, and is not user friendly: change jamtaba version to 2.1.0. JamTaba server will not accept the older versions, and all users will be **forced** (this is the problem) to upgrade, avoiding the crash when receiving video intervals.

**Comment by jonjamcam** [comment]
> Right now I can see just one solution, and is not user friendly: change jamtaba version to 2.1.0.

Yeah, pretty drastic. I did another test inverting versions on each computer, but the crash is unavoidable in 2.0.20 as soon as the camera is turned on, so probably it's time for 2.1 as you say

**Comment by jonjamcam** [comment]
@elieserdejesus I'm trying to set up msvc from the link you posted above, but I really don't know which of these to download:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , in this [page](https://www.visualstudio.com/pt-br/productinfo/vs2013-sysrequirements-vs) win 7 SP1 is listed as supported. 

I downloaded msvc long time ago, but my guess is **Visual Studio Express 2013 for Windows Desktop** or the **Visual Studio Express 2013 for Windows** (in the bottom).

**Comment by jonjamcam** [comment]
@elieserdejesus  looks the desktop version will install XD

image

**Comment by elieserdejesus** [comment]
@jonjamcam , after install msvc you have 2 options:

**The easy way (can compile JTBA Standalone only)**:  download and install qt for msvc 2013.
**The NOT easy way (can compile VST plugin)**:  you need compile Qt statically using the msvc compiler. It's a pain as you know. 

I can send my Qt staticaly compiled, but unfortunally Qt for windows can't be moved for another folder after compiled. I'm using my Qt inside **E:\Qt\Qt5.5.0-64bits**. If you have an **E:** drive in your machine (or can simulate) we can try this option. Have you an E: drive or some possibilty to create an E: and the folders I mentioned?

**Comment by jonjamcam** [comment]
I installed msvc2013 and qt recognizes the compiler, but build gives me an error:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , can you create a new Qt projeto in QtCreator? Try create a Qt Widgets project (using the template proposed by QtCreator in NEW menu) and see if QtCreator can compile the project using your Qt. If yes, the problem is in JamTaba build files.

Your folder **C:/Qt/Qt5.5.1/5.5/Src/qtbase/lib** contain msvc or ming@ compiled files? The mingw libs are using **.a** entensions, and the msvc libs are using **.lib** extensions.

**Comment by jonjamcam** [comment]
> Your folder C:/Qt/Qt5.5.1/5.5/Src/qtbase/lib contain msvc or ming@ compiled files? The mingw libs are using .a entensions, and the msvc libs are using .lib extensions.

only .a and .prl. there's no .lib

**Comment by elieserdejesus** [comment]
> @elieserdejesus maybe I need to install this Qt version?

Exactly @jonjamcam , pick this **Qt MSVC 2013**.

**Comment by jonjamcam** [comment]
@elieserdejesus It's compiling using msvc now. Cool. I'm not able to compile static though yet, but a least I will be able to test as always the standalone version. Thx, man.

**Comment by elieserdejesus** [comment]
> It's compiling using msvc now. Cool. I'm not able to compile static though yet, but a least I will be able to test as always the standalone version. Thx, man.

Nice @jonjamcam , you are welcome! If you still have patience (a lot 😄) I can help you compiling Qt statically.

**Comment by jonjamcam** [comment]
> If you still have patience (a lot :smile:) I can help you compiling Qt statically.

Yeah I have a lot of patience @elieserdejesus lol. Let's do it.

**Comment by elieserdejesus** [comment]
@jonjamcam , I build a step by step instructions here, please help fixing the typos and including missing parts. The ideia is put these instructions in the README.md.

I'm pointing to Qt v 5.5.1, just be exactly the version I'm using here. Maybe newer version need some changes in the steps.

***

1 - Download **Qt Sources**, but **only submodules** used by JamTaba. This will speed up the compilation. The sources are in [http://download.qt.io/archive/qt/5.5/5.5.1/submodules/](http://download.qt.io/archive/qt/5.5/5.5.1/submodules/)

	Download the files:

	1 - qt5-opensource-src-5.5.1.zip
	2 - qtbase-opensource-src-5.5.1.zip
	3 - qtmultimedia-opensource-src-5.5.1.zip
	4 - qttools-opensource-src-5.5.1
	

2 - Extract the dowloaded files in your preferred **Qt folder**, for example C:/MyQt. All files will be extracted inside **4 subfolders**.

3 - Rename the extracted subfolders removing the suffix **-opensource-src-5.5.1**. The renamed folders will be **qtbase**, **qtmultimedia** and **qttools**.  It's not necessary rename the folder **qt-everywhere-opensource-src-5.5.1** (see the next step).

4 - Move all files inside the folder **qt-everywhere-opensource-src-5.5.1** the your Qt folder and delete the folder **qt-everywhere-opensource-src-5.5.1**. The final folders/files layout will be:

- Your Qt Folder
image


5 - In your Qt folder create a file named **qt5vars.cmd** using a text editor (notepad). Paste these script lines in this file, but **REMEMBER** to change the **_ROOT** from "C:/MyQt" to your real "Qt folder" path:

```
	CALL "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
	SET _ROOT=C:/MyQt

	SET PATH=%_ROOT%\qtbase\bin;%_ROOT%\gnuwin32\bin;%PATH%

	SET QMAKESPEC=win32-msvc2013
	SET _ROOT=
```

6 - Open the windows prompt (cmd) and navigate to your Qt folder. The command to navigate is **cd C:/QtMyQt**


7 - Run the script file created in the step 5 to setup MSVC. In the command prompt type **qt5vars.cmd** and press ENTER. After some seconds you will see 2 lines in the prompt, and the prompt will be waiting for new commands. **IMPORTANT**: This script is setuping MSVC to compile in 64 bits.

8 - Now, copy and paste these scripts line in your prompt and press ENTER to execute (this script will configure Qt just with the modules used in JamTaba):

```
configure -debug-and-release -opensource -confirm-license -static -no-sql-psql -no-sql-mysql -no-sql-odbc -no-sql-tds -no-sql-oci -no-sql-db2 -no-sql-sqlite -no-sql-sqlite2 -no-sql-ibase -no-audio-backend -no-cups -no-nis -no-dbus -nomake examples -nomake tests
```


	After some seconds you will see **2 messages**:

		Qt is now configured for building. Just run nmake.
		To reconfigure, run nmake confclean and configure.

9 - Just follow the message, type the command **nmake** in your prompt and press ENTER. Drink a coffee, the compilation lasted **90 minutes** here.

10 - After 90 min the job is done, check your Qt folder, **inside the qtbase** folder you have all Qt static libs compiled.

**Comment by jonjamcam** [comment]
@elieserdejesus Got the plugin compiled and working!

image

The explanation above was perfect!

**Comment by elieserdejesus** [comment]
> @elieserdejesus Got the plugin compiled and working!

Very nice news @jonjamcam !

Can you fix my english and add the compilation instructions in the **README.md**?

**Comment by jonjamcam** [comment]
> Can you fix my english and add the compilation instructions in the README.md?

Sure I do that @elieserdejesus . I suppose I fix my local readme.md and then you copy it like the manual?

**Comment by elieserdejesus** [comment]
> I suppose I fix my local readme.md and then you copy it like the manual?

@jonjamcam, the steps to edit README.md are the same to edit a C++ or css source code. Just edit the file in your fork (you can use the github online editor too), commit and propose a pull request.

**Comment by jonjamcam** [comment]
@elieserdejesus Today I did a test with Jamtaba 2.0.18 and there's no crash here when using video in 2.1.0. The problem happens with 2.0.20. I still have not tested 2.0.19 or 2.0.17 and earlier.

**Comment by elieserdejesus** [comment]
@jonjamcam , thanks for these tests. 

2.0.20 is the most downloaded version. Without force an update (with 2.1.0) a lot of people will crash.

**Comment by jonjamcam** [comment]
Yes. True. Btw do you think beta testers of 2.1.0 know about this issue?

**Comment by elieserdejesus** [comment]
@jonjamcam , the beta versions are not very popular :). I have a small script getting download counters from github:

image

**Comment by jonjamcam** [comment]
Good. I just told andy about the incpmpatibility in case he wants to test

**Pull request merged**
