### PR TITLE
qtbase_es and qtbase_pt translations

### PR DESCRIPTION
**Pull request by jonjamcam**
@elieserdejesus The Spanish translation I downloaded from http://l10n-files.qt.io/l10n-files/ was not empty. I started the translation in order to complete it, but it looks that for Jamtaba's needs it's complete enough at the moment. Sure I will update when finished.

EDIT: I also included the qtbase_pt in this PR. Although it's not complete it's working fine in Jamtaba.

### CODE REVIEW

**Comment by elieserdejesus** [comment]
Thanks @jonjamcam , I tested here and the missing translation for ES and PT are working ok now. Can I merge or are you planning more updates in this PR?

**Comment by jonjamcam** [comment]
> are you planning more updates in this PR?

No more updates for the moment. I do plan to complete the translation in the future though and send it to QT (and update jamtaba too), but it will take some time. It's kind of big.

**Comment by elieserdejesus** [comment]
Ok @jonjamcam , I was investigating how build Jamtaba VSt Plugin for Mac Osx, but now I'm convinced Qt is not the best tool to develop audio driven applications like Jamtaba. 

At moment is just an idea, but I'm considering rewrite Jamtaba using [JUCE](https://www.juce.com/).

I will generate the v.2.018 installers, thanks again!

**Comment by jonjamcam** [comment]
>At moment is just an idea, but I'm considering rewrite Jamtaba using JUCE.

@elieserdejesus In this case it would mean a completely different GUI? or your idea of using JUCE is for Mac Vst only?

**Comment by elieserdejesus** [comment]
@jonjamcam , a completely different GUI code is necessary, but is possible keep the same visual result. Other codes need be changed too, so is a lot of work, it's not just the GUI code. 

I'm still trying to get VST PLugin running in Mac, but is a pain. Qt is not designed to these type of applications, a lot of workarounds are necessary to get Qt working fine in Host environments.

**Pull request closed without merging**
