### PR TITLE
Fixing 'start from focused layer'

### PR DESCRIPTION
**Pull request by elieserdejesus**
- Fixing 'start from focused layer'
- Fixing the auto tests too

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , this PR is fixing the 'start from focused layer issue'. Can you test before the merge, please?

**Comment by jonjamcam** [comment]
@elieserdejesus The layer selection works OK now in locked layers, but my tests show that the "recording focus" is lost. Now it's not possible to focus any other layer for recording independently from the selected layer.

**Comment by elieserdejesus** [comment]
@jonjamcam , can you test the last commit in this PR? I fixed the record issue.

**Comment by jonjamcam** [comment]
> can you test the last commit in this PR? I fixed the record issue.

Working OK now @elieserdejesus

**Comment by elieserdejesus** [comment]
thanks @jonjamcam !

**Pull request merged**
