### PR TITLE
Fixing themes exporting 

### PR DESCRIPTION
**Pull request by elieserdejesus**
- Trying to export every CSS theme file in resources folder when Jamtaba is started. A CSS file will be exported in 2 conditions:
	1 - if the file NOT exists in user appData folder OR
	2 - the file in resources folder is newer (checking the lastEdited atribute) then same file in user appData folder.

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , can you test the PR please? I tested Standalone and VST plugin, it's work fine here. 

- If you delete a theme folder this folder will be recreated in next session. 
- If you delete a single file inside some theme folder this file will be recreated.
- If you recompile JamTaba all theme files will be exported in next session because now the resources files are newer than your appData files.

**Comment by jonjamcam** [comment]
My first test didn't work. I did a little modification to **Ice/General.css**  inside QtCreator and compiled to see the result:

1.- Check files in the **Themes dir**:

image

They all have same date (from two days ago).

2.- Compiling Jamtaba with variation in **General.css**. The corresponding **resource file** changed as expected:

image

All good at this point.

3.- Once Jamtaba is Launched I checked the **Themes dir** for the updated **General.css** file, but the file is still the old one :( : 

image

**Comment by elieserdejesus** [comment]
> If I understood correctly, in this example all files should be new, not just General.css, but that was not the case.

Yes @jonjamcam , this is the expected behavior.

I have a suspect:
- I changed the application name from Jam**t**aba 2 to Jam**T**aba 2. Can you check if you have 2 folders in your appData? Jamtaba and JamTaba ? If not, try delete your Jamtaba folder and see if the theme export problem is solved.

**Comment by jonjamcam** [comment]
>Can you check if you have 2 folders in your appData?

I have only one folder callled "Jamtaba 2"

>try delete your Jamtaba folder and see if the theme export problem is solved.

OK. I deleted the fikder "Jamtaba 2". Now after relaunch the folder name changed to "JamTaba 2". 

I repeated the same steps than before again, but it's not working. The .css files in the **themes folder** remain unchanged after compilation.

**Comment by elieserdejesus** [comment]
@jonjamcam , I pushed a commit adding some log lines to understand why the theme exporting is not working in your machine. Can you update your branch and test again?

**Comment by jonjamcam** [comment]
> Can you update your branch and test again?

OK. I compiled having changed the **general.css** file in the resources folder:

image

This is the log:

[log.txt](https://github.com/elieserdejesus/JamTaba/files/720220/log.txt)

**Comment by elieserdejesus** [comment]
@jonjamcam , I'm using some C++ macros (magic functions) to get the compilation time. These macros are __DATE__ and __TIME__. I'm suspecting the conversion of these macros to Qt class QDateTime is failing in your machine, maybe something related with your Locale. 

I added more log lines showing the value of __DATE__ and __TIME__ macros and showing the respective converted values in Qt.  I test the code in my mingw and works, the macros are C++ ISO, cross plataform, etc. So it's not a compiler issue.

Can you test again, please?

**Comment by jonjamcam** [comment]
Sure. I did a clean just to be sure, but this happened:

image

**Comment by jonjamcam** [comment]
I tested deleting the Ice folder and the good news id that this part is working OK. The Ice Folder is created.

 I tested in the other win10 laptop (that has the "Jamtaba 2" folder, not "JamTaba") and the Ice folder is also created. But no changes to specific file are made here, same as in win7.

**Comment by elieserdejesus** [comment]
@jonjamcam , I see the problem in your log now:
```

C++ dateTime macros:  ' Jan 20 2017 '   ' 16:36:25 '
compilation date:  QDate("")
compilation time:  QTime("16:36:25.000")

```

QTime is ok, but **QDate is empty**, some problem in conversion. Will investigate this issue.

**Comment by elieserdejesus** [comment]
@jonjamcam , can you run another test? I changed the date conversion code and cleaned the log.txt. I added some color codes in log. The log colors works nice in QtCreator console, but messed the log.txt. It's ok now.

**Comment by jonjamcam** [comment]
It's working! Great Job @elieserdejesus ! The log:

[log.txt](https://github.com/elieserdejesus/JamTaba/files/720594/log.txt)

Before:

image

After:

image

**Comment by elieserdejesus** [comment]
nice @jonjamcam , thanks for your help!

**Pull request merged**
