### PR TITLE
Alowing 'hear all/locked' in Selected Layer mode

### PR DESCRIPTION
**Pull request by elieserdejesus**
- Allowing 'hear all/locked' in Selected Layer mode
- Fixing auto tests

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , this PR is implementing 'hear all/locked' in **Selected layer** looper mode. Can you test, please?

**Comment by jonjamcam** [comment]
@elieserdejesus Yeah it works good for all layers, but as this mode does not allow playing locked layers I think it's not complete. Do you think it's a good thing to allow the "play locked" checkbox to be available too only if "hear all/locked is" used? So to be able to have both choices.

**Comment by elieserdejesus** [comment]
done @jonjamcam , can you check again?

**Comment by jonjamcam** [comment]
The implementation is working great now @elieserdejesus . But unfortunately I have a recurring crash when selecting All layers mode.

**Comment by elieserdejesus** [comment]
crash fixed @jonjamcam .

**Comment by jonjamcam** [comment]
Works great!

**Pull request merged**
