### PR TITLE
Fixing keys in sonar x3

### PR DESCRIPTION
**Pull request by elieserdejesus**

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@Trashcanhead1111, I fixed the typing problems in numbers and numpad. The question mark is working ok here too. Can you test, please?
[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/444908/JamtabaVST2.zip)

**Comment by Trashcanhead1111** [comment]
I think the ? mark when shift key held is still not working. but number pad and others seem to be ok

**Comment by elieserdejesus** [comment]
@Trashcanhead1111 , here in my laptop the question mark is working fine. I supose we are using different keyboard layouts. Can you post a picture (or a link to a picture) of your keyboard? I'm trying understand why your question mark is not working.

In my keyboard the "?" only work with SHIFT key pressed.

**Comment by Trashcanhead1111** [comment]
its just a dell pc keyboard with number pad . 025pgg is model number. here is a google for images.
on teamviewer to drum room laptop im not getting a ? mark either. but maybe cause its using keyset for dell keyboard ?.?
just put sons gaming keyboard on pc and no go as well. sorry to trouble you with it. 
i can make the slash with same key but shift wont give the ? mark


https://www.google.com/search?q=dell+025pgg&espv=2&biw=1920&bih=965&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiP-tfE3O_OAhUG9x4KHVN9DjoQ_AUICCgD#imgrc=rlx1Y6cE50qacM%3A

**Comment by elieserdejesus** [comment]
@Trashcanhead1111 , I tested here using a USB keyboard, same layout as your 025pgg model, the question mark key is in left side of right shift key. It's working ok in my laptop keyboard and in this USB keyboard.

I will close this thread for while, until we have more clues to understand your problem. I'm suspecting this is something more specific in your keyboard or machine.

**Comment by Trashcanhead1111** [comment]
I dont understand why it works with all other versions though. i can even swap back and forth between versions and one works one doesnt.

**Comment by elieserdejesus** [comment]
@Trashcanhead1111 , 
In this [link](http://www.delphiforfun.org/Programs/Utilities/KeyCodes.htm) you can download a small program to inspect the key codes of your keyboard. Can you help me running this program and reporting the key code for your "?" key?

The steps are:
1 - Run the program
2 - Press the "?" key (using SHIFT if I remember correctly)
3 - Copy and paste the text generated in the programming here.

**Comment by Trashcanhead1111** [comment]
OnKeyDown, Key code=16, Control keys=Shift{Left}, Key name SHIFT
OnKeyDown, Key code=191, Control keys=Shift{Left}, Key name ........OEM specific
OnKeyPress ?
OnKeyup, Key code=191, Control keys=Shift{Left}, Key name ........OEM specific
OnKeyup, Key code=16, Control keys=, Key name SHIFT

**Comment by elieserdejesus** [comment]
Thanks for the infos @Trashcanhead1111 , these are my results here, as you can see the keycode the question mark (*193*) is not the same:
```
OnKeyDown, Key code=16, Control keys=Shift{Left}, Key name SHIFT
OnKeyDown, Key code=193, Control keys=Shift{Left}, Key name Unassigned
OnKeyPress ?
OnKeyup, Key code=193, Control keys=Shift{Left}, Key name Unassigned
OnKeyup, Key code=16, Control keys=, Key name SHIFT
```
I will check this issue again soon.

**Comment by elieserdejesus** [comment]
@Trashcanhead1111 , can you test the question mark key again, please?

[JamtabaVST2.zip](https://github.com/elieserdejesus/JamTaba/files/457665/JamtabaVST2.zip)

**Comment by Trashcanhead1111** [comment]
yes that worked. thanks .really appreciate your time on it.  so good so good :)

**Comment by elieserdejesus** [comment]
nice news @Trashcanhead1111 !

**Pull request merged**
