### PR TITLE
fixed gap in master volume controls

### PR DESCRIPTION
**Pull request by jonjamcam**
this PR fixes issue https://github.com/elieserdejesus/JamTaba/issues/252

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , I merge your pull request but my name/user appears in the commit, and your name not appear in the contributor list. I reverted the pull request to try again, but is not possible.

Please, can you create the pull request again? I'm trying merge your work without change the author.

**Comment by elieserdejesus** [comment]
Jom, I see the commit author is **jam** but your username is **jonjamcam**. Maybe this differents names are causing some problem in the merge. If possible try commit as **jonjamcam**.

**Comment by jonjamcam** [comment]
@elieserdejesus I've been trying to commit with **jonjamcam**, but it looks git already chose **jamp** by default and although the instructions to change it seem very simple, I've tried unsuccessfully to do it. This screen I can't understand, but it's where I change the name:

git screen change name

BTW Don't worry. I'm happy to contribute as I'm doing now. If I can fix this we can try again in the future another commit.

My reward is learning some code and the experience of jaming with Jamtaba. The sound is really unique for a ninjam client.

**Comment by elieserdejesus** [comment]
Jon, you can change your git user name globally, try [this link](https://help.github.com/articles/setting-your-username-in-git/), the second example show how set the name and email globally.

I'm learning these git stuff too, I'm not a expert. I'm trying understand why sometimes the author of commit appears in the commit history in sometimes not. For example, some days ago a JamTaba contributor created a pull request renaming some files to start the Linux port. I just clicked in the github "merge pull request" button and the result is what I expected:
image

I tried the same thing in your pull request and the result was different (me as author). And I see a 3rd variation when I integrated a contribution writed by Tea. The result was a hybrid (me and Tea):
image

After some reading I learned git has two roles: the **author** and the **commiter**. I'm searching for a clean way to integrate the contributions and preserve the author and commiter infos.

**Comment by jonjamcam** [comment]
@elieserdejesus . Followed your link. It looks the name was changed successfully now.

git name chg jonjamcam

and the commit appears with correct name now:

commit with jonjamcam
 

Creating a new PR. Hope it works now.

**Comment by elieserdejesus** [comment]
Nice, thanks! testing right now!

**Comment by elieserdejesus** [comment]
Thanks Jon, now your name is correctly in the contributors list and in the commit history:

image

Feel free to create another pull requests!

**Comment by jonjamcam** [comment]
Cool! thx.

**Pull request merged**
