### PR TITLE
Widen looper window size

### PR DESCRIPTION
**Pull request by jonjamcam**

### CODE REVIEW

**Comment by jonjamcam** [comment]
@elieserdejesus I tested this looper window size and it's the minimum size for all translations to fit. It was quite a change +10%

**Comment by elieserdejesus** [comment]
OK @jonjamcam , please tell me when this PR can be merged.

I tested the new looper window width and is nice.

I see the looper window is not translated when I choosed a new language in menu. Can you confirm this issue? If I restar Jamtaba with another language selected the looper window translation work ok.

**Comment by jonjamcam** [comment]
> I see the looper window is not translated when I choosed a new language in menu. Can you confirm this issue? If I restar Jamtaba with another language selected the looper window translation work ok.

Yes. That is exactly what happens in my system too.

**Comment by elieserdejesus** [comment]
> Yes. That is exactly what happens in my system too.

Ok, I will create a issue for this, just to remember myself :)

**Comment by jonjamcam** [comment]
@elieserdejesus it looks the size is working OK for the new French translation:

image

You can merge the PR, no problem.

**Comment by elieserdejesus** [comment]
thanks @jonjamcam !

**Pull request merged**
