### PR TITLE
es_CL-locale-update

### PR DESCRIPTION
**Pull request by jonjamcam**
Time for a new locale update?

### CODE REVIEW

**Comment by elieserdejesus** [comment]
Merged in master, thanks Jon!

**Comment by teamikl** [comment]
@elieserdejesus @jonjamcam 
we need discussion when to update *.ts files?

I have translate-ja_JP branch to maintain ja_JP.ts
I can make PR though, can pick from elieser side?

**Comment by jonjamcam** [comment]
> we need discussion when to update *.ts files?

@teamikl .I think I send it a bit earlier, my bad. I apologize. I remember we agreed that it was going to be the last thing to do. I was working on the update because I had some ideas of syntax that I didn't want to forget. I should have waited to be asked for it. Won't happen again.

So to remember (mostly me) We'll wait for Elieser to tell us when to make the PR when he's ready for a release?

**Comment by teamikl** [comment]
@jonjamcam 
no problem, it's small cost if new text resource added you have to make PR again.
I am not sure though, I checked Milestone v2.14.0 seem rest tasks has no new UI.

my propose:

1. work on `translate-(locale)` branch
2. **Elieser run lupdate and commit *.ts file to upstream master.**
3. checkout translate branch and `git merge master`
4. (if need locations) lupdate with -locations relative option. this will give preview UI/src on Linguist
5. linguis and edit ts file
6. build test
7. (if locations generated) lupdate with `-locations none` option to strip filename/lineno
8. push the branch to remote
9. make PR (or Elieser pick?)

update *ts files on master can be the signal when to translate update.
this can avoid `git add ./translations` to commit unnecessary *.ts files.

**Comment by jonjamcam** [comment]
good idea! That way there's going to be a branch with all translations for review purposes. This way we keep the current workflow.

**Comment by elieserdejesus** [comment]
@teamikl and @jonjamcam 

> I am not sure though, I checked Milestone v2.14.0 list seem rest tasks has no new UI.

The issue #309 will generate a new string to TS files. 

@teamikl , about the proposed workflow:
The second step is necessary? You or Jon can run **lupdate**, right?

> make PR (or Elieser pick?)

I prefer a PR, but both models can work if we send a message to each others. For example, you can commit a update in translation branch and add a comment in the commit with a mention for @elieserdejesus.

I have another suggestion for **when to update *.ts files?**
At the end of tasks (or at the end of GUI related tasks) I can create a PR commiting my pt_BR translations changes and mention all the translators asking for the updates. To create a PR I need create a new branch and you can commit your changes in this branch too. Magnus and DoubleBass can upload the translated TS files in a PR comment. We can organize all translation tasks in a PR. 
**What you think about?**

**Comment by teamikl** [comment]
@elieserdejesus 
> The second step is necessary? You or Jon can run lupdate, right?

of cause we can.
but that make another TS files which we should not add to commit. 
lupdate will change all TS files,
If master has updated TS files, that can avoid another TS files added by mistake.
we can add only the translation file safely by `git add ./translations` command.

1 PR for all translations is good.
then can you cherry-pick TS files from our remote branch ?

**Comment by elieserdejesus** [comment]
@teamikl , I understand now.  So the translation work flow can be something like:

0. Elieser run lupdate and commit *.ts file to a new branch **translations for version <VERSION_NUMBER>**.
1. A **PR** will be created from the branch created in first step and the translators will be asked to update your translations.
2. Translators will work on translate-(locale) branch
3. checkout translate branch and git merge master to update the translate-(locale) branch
4. (if need locations) lupdate with -locations relative option. this will give preview UI/src on Linguist
5. linguis and edit ts file
6. build test
7. (if locations generated) lupdate with -locations none option to strip filename/lineno
8. push the branch to remote
9. Add a coment in the PR created in first step to communicate your translation work is done.
10. Elieser will pick your translation commit from your remote branch.

**Pull request closed without merging**
