### PR TITLE
[WIP] Volcano theme

### PR DESCRIPTION
**Pull request by elieserdejesus**
Working in a "volcano" theme based in the FAbfilter Volcano VST plugin colors:

image

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , I pushed the 2 commits of "volcano" theme. I worked only in the first window, all details (hover effects, menu, ninjam window, dialogs, etc) are not changed.

I like the general result, but I'm not shure about some details. The border color in local track buttons and slider is too "red" in my eyes. I think a "more black" color will work better.

Please fee free to improve!

**Comment by elieserdejesus** [comment]
@jonjamcam , I added a new property in public rooms to allow different colors when the room is empty. The idea is keep the focus in "populated" rooms:
image

**Comment by jonjamcam** [comment]
Nice colors! The transparency of the room panels looks really good.

@elieserdejesus What do you think it's the best workflow following. Should I use the old Fire PR for the pending details?

**Comment by elieserdejesus** [comment]
@jonjamcam , you can **pull** these commits in top of your PR, but I'm 99% shure you will have a lot of git conflicts to solve manually, because we edited same stylesheet files.

I think the most easy and clean work flow is:
1 - folow the github instructions to pull this PR commits. Now you have a new local branch with my 3 commits.
2 -  Send me a message and I will delete this PR and the associated remote branch.
3 - Now you can create a new PR using the previous "downloaded".

**Comment by jonjamcam** [comment]
@elieserdejesus I think I found a problem with the new feature (allow different colors when the room is empty). it is working OK when launching Jamtaba, but as soon as the server refresh, the effect is lost:

image

image

The room name color is not kept either in this case. Does this happen to you too?

**Comment by elieserdejesus** [comment]
It's fixed in the last commit @jonjamcam .

**Comment by jonjamcam** [comment]
Working now @elieserdejesus . I found another problem related.  The effect is not preserved when changing to other theme and going back in this specific case only:

1.- Open Jamtaba using Volcano Theme
2.- Wait until the server refreshes waiting about 1 minute (The effect is still preserved)
3.- Change to other theme
4.- go back to Volcano. Now the effect is gone.

Maybe this happens because the other themes do not have specific code related to this enhancement? Just a guess.

**Comment by elieserdejesus** [comment]
it's fixe @jonjamcam , just a simple problem when verifying if the room is empty or not.

**Comment by jonjamcam** [comment]
@elieserdejesus I find the theme is really great! So far it's my favorite one, but I don't know how to finish it.

 I think palettes and where you place each color are really personal decisions. There are no rules as long as the result has an effect, but to me some details are not matching with the overall palette:

image

I would change the **chat background** and **ninjamer Top Panel** for example, but I can't think which color.

 Some other suggestions too:

1.- channel name local track unlighted: 

rgba(0, 0, 0, 10);

image

or 

**rgba(255, 106, 0, 100)**

image

2.- Unselected Room Tab

image

***

I found another little problem with the new feature (transparency for empty rooms). If the rooms are all empty when jamtaba is launched (semi-transparent) and someone drops in one room, the higlight effect is not applied.

**Comment by elieserdejesus** [comment]
@jonjamcam 
> but to me some details are not matching with the overall palette.

I changed just the colors in the "start" screen. The chat, tabs, hover effects, ninjam window are not touched and I agree the colors are not matching. I started Volcano theme based in Flat theme, so the "wrong" colors are from Flat theme. I agree all details you pointed in your first image are not matching and need be changed.


> I would change the chat background and ninjamer Top Panel for example, but I can't think which color.

For chat background I suggest the same color used in left panel as a start point. This will be an automatic color match in overall color scheme. I used a rule in the left panel background: the background color in the left panel is the foreground color in (non empty) public rooms. [Color palletes](http://www.colorcombos.com/orange-color-schemes.html) contain just 4 or 5 colors, so invert colors is a good trick to reuse colors and keep the visual identity.

For ninjam top panel I will suggest a transparent trick I used a lot: **rgb(0, 0, 0, 10);**. This will be a black color with 10 (from a max of 255) of transparency. The final result will be the same background color, but slightly dark. If the background is orange we will see a slightly dark orange. I think this transparency trick is good to avoid add new colors in the pallete. Using transparency we have good effects just playing with variations of 4 or 5 basic pallete colors.

> Some other suggestions too: 1.- channel name local track unlighted: rgba(0, 0, 0, 10);

I prefer this option than your second option to unlighted track.

> 2.- Unselected Room Tab

I will suggest some transparency trick (*rgb(0, 0, 0, 20)*) in the unselected tab.

@jonjamcam , I think the 2 general rules I followed in this theme are:
1 - try keep a small pallete (4 or 5 basic colors)
2 - explore the basic colors variations (transparency tricks) to create subtle effects, avoid add new colors in the pallete.

**Comment by elieserdejesus** [comment]
> I found another little problem with the new feature (transparency for empty rooms). If the rooms are all empty when jamtaba is launched (semi-transparent) and someone drops in one room, the higlight effect is not applied.

I will check this bug.

**Comment by elieserdejesus** [comment]
@jonjamcam , the bug in public rooms update is fixed.

**Comment by jonjamcam** [comment]
This is the result:

* channel name local track unlighted: rgba(0, 0, 0, 10);
* Unselected Room Tab: rgb(0, 0, 0, 20);
* chatTabWidget:pane, chatTabWidget :  background-color: #BD5A1D;

image

I think the best option is to use this PR till the end. There are some important commits here.

**Comment by elieserdejesus** [comment]
Nice @jonjamcam. I don't like the gray borders, and the gray is not matching with the orange pallete in general.

Some suggestions:
1 - Change the border color of ninjam window buttons (in top right) to match local track button border color.
2 - Change the ninjam panel border (the panel in bottom center, used to show the interval progress circle) to match the previous item in this list.

Now I think is necessary allow change the interval progress color (current is gray) in stylesheet.

@jonjamcam , I'm not 100% happy with the background color in the bottom area. I think we need some more orange/red, more hot. What you think?

**Comment by jonjamcam** [comment]
> I'm not 100% happy with the background color in the bottom area. I think we need some more orange/red, more hot. What you think?

The first version you made of this theme had the red bottom panel:



 Looks good, but I like the contrast it has now, That difference makes the red/orange in the background somehow special.

For example, which picture below would you use to focus attention in the black sheep?



or



I think we discussed before. The name of the game is **contrast** :smile:

**Comment by elieserdejesus** [comment]
@jonjamcam , are you still working in this theme? I will release the 2.0.17 to fix the bugs in 2.0.16 and I think will be nice release this new theme too. Any progress?

I need fix this branch, it's conflicting with master at moment.

**Comment by jonjamcam** [comment]
@elieserdejesus I can continue in my "fire" branch if needed.

**Comment by elieserdejesus** [comment]
@jonjamcam 
>  I think the best way to do this is for you to merge this PR an then I pick it up from there and finish it in a new PR

I pushed a new commit in this PR fixing the conflicts. Can you continue from this branch? 

> When are you planning to release the 2.0.17? I can have the theme finished by tomorrow morning.

The new theme is the last task. But this time I will create a pre-release and invite you, Doublebass and Trashcanhead to test the pre-release before publish the official version, just to avoid a new buggy release. The v2.0.16 was premature, unfortunally.

**Comment by jonjamcam** [comment]
>Can you continue from this branch?

Sure. I have my work saved locally.

**Comment by elieserdejesus** [comment]
@jonjamcam , is possible use individual commits from your local branch using **git cherry-pick". 
For example, supose you pulled this branch to your machine. Now you have the commits in this PR branch, but your local work is not in this branch. You can **checkout** your local branch and use **git log -5** to see the 5 last commts in your local branch. Find the commit you are interested and copy the **commit hash code**. Now you can back to **this PR branch** using **git checkout** and run a **git cherry-pick HASH_CODE_HERE**. Using this trick you can "join" your local commits, no need to copy paste the changed source code.

Is possible use **git cherry-pick** to get a commit range too, very usefull too.

**Comment by jonjamcam** [comment]
good to know the cherry pick command. But for this specific theme I didn't use commits. I just did some more work (handles, etc.) and I made a rar file of the whole folder :D. There's very little to do to finish, so far my list has:

change subchannel color
connecting with server dialog
server title border
handles hover
faders hover
buttons hovers
preferences dialog
menu colors
channel name background focus color

I will work on these tonight.

**Comment by jonjamcam** [comment]
@elieserdejesus I'm testing this branch now, but the "empty room" color differentiation is not working.

**Comment by elieserdejesus** [comment]
@jonjamcam , I do some mess when fixing the conflicts. I will fix this problem soon.

**Comment by elieserdejesus** [comment]
@jonjamcam , now this branch is ok (I hope). Please drop your old version and pull these commits again.

**Comment by jonjamcam** [comment]
@elieserdejesus Working OK now.

**Comment by jonjamcam** [comment]
> Now I think is necessary allow change the interval progress color (current is gray) in stylesheet.

(https://github.com/elieserdejesus/JamTaba/pull/507#issuecomment-235674505)

@elieserdejesus are you planning to do this one? It's the only gray color I've found so far

image

**Comment by jonjamcam** [comment]
@elieserdejesus I completed the Volcano theme. Here's the files:

[Volcano02sept2016_C - copia.rar.txt](https://github.com/elieserdejesus/JamTaba/files/452580/Volcano02sept2016_C.-.copia.rar.txt)

Now you can complete this PR for review the next days :D

**Comment by elieserdejesus** [comment]
@jonjamcam , I pushed a commit integrating your changes.  As you can see the commit is in your name, is possible [commit as another person in git](http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit).

I have a suggestion for another work flow for this PR: 
1 - Pull this branch commits for a local branch in your machine.
2 - Push these commits for your fork. Now you have a "clone" of this branch in your fork.
3 - I will delete this PR and branch.
4 - You create a PR based in your "cloned" branch. Now you can push your commits directly in your branch (in your fork), no need to send .rar files, etc.

Just send a message when you have cloned the branch in your fork and I can delete this PR and the branch.

**Comment by jonjamcam** [comment]
@elieserdejesus Don't you think the best solution is to merge the PR? I rather avoid messing things up if I make a mistake. I've lost work in the past using git wrongly.

**Comment by elieserdejesus** [comment]
no problem @jonjamcam , I will merge.

**Pull request merged**
