### PR TITLE
Themes

### PR DESCRIPTION
**Pull request by elieserdejesus**
@teamikl and @jonjamcam , I'm adding a last feature in 2.0.14, theme selection. Allowing 2 themes at moment, a third orange theme is unfinished:

image

Flat theme:
image

image

### CODE REVIEW

**Comment by jonjamcam** [comment]
Themes are very nice! how are they created?

**Comment by teamikl** [comment]
@jonjamcam 
Qt provide styleshee http://doc.qt.io/qt-5/stylesheet.html
I tried it was easy, add CSS file into resource then JamTaba will show on Theme menu
NOTE: real css file is under resources directory, resource path is ./style/*.css

#### QtCreator
- open Standalone.pro and expand the tree Jamtaba-common / Resource/ jamtaba.qrc
- right click /style and add new file then General -> Empty File
- location path is Jamtaba/src/resources, file name with suffix .css (e.g. Test.css)
- add to project jamtaba.qrc prefix: /style

copy exist CSS file content and use them as starter template.

#### Manual
- create ./src/resources/Test.css file
- add the entry to ./src/resources/jamtaba.qrc

@elieserdejesus 
do you plan user customize Theme?
as quick way for now, allow user -stylesheet option for debug build will be useful for theme creators.

**Comment by jonjamcam** [comment]
Great info Tea! Thx.

**Comment by elieserdejesus** [comment]
@jonjamcam , Tea explained very well how themes are created.

Tea mentioned
> Copy exist CSS file content and use them as starter template.

I recommend copy the file **Flat.css**, it's less messed then **Rounded.css**, but both files are messed :)  I will clean these files in the next round.

> @elieserdejesus do you plan user customize Theme?

Yes Tea, in the PROJECTS dir you can see a ThemeEditor, but it's just a scratch/idea, nothing usefull at moment.

> as quick way for now, allow user -stylesheet option for debug build will be useful for theme creators.

Tea, I don't understand the part **allow user -stylesheet option for debug build**. Can you elaborate, please?

**Comment by teamikl** [comment]
@elieserdejesus 
>  allow user -stylesheet option for debug build. Can you elaborate, please?

Qt application has that command line arguments to read user css file by default.
it's implemented in QApplication app(argc, argv)

The Theme CSS now override the command line -stylesheet option.
So, this proposal will allow user to set own CSS file, make easy to debug custom CSS.

```cpp
bool loadCSS = true;
#ifdef QT_DEBUG
    loadCSS = app.styleSheet().isEmpty();
#endif
if (loadCSS)
    app.setStyleSheet(...);
```

apply custom css file with `Jamtaba2.exe -stylesheet Test.css`
no need rebuild to apply the changes.

> will clean these files in the next round.

consider AltCSS for the simplify?

**Comment by elieserdejesus** [comment]
@teamikl 
> apply custom css file with Jamtaba2.exe -stylesheet Test.css no need rebuild to apply the changes.

Understand now, thanks! This is a good idea. I will create a issue to avoid loose this idea in the "jungle" (by Magnus) :)

> consider AltCSS for the simplify?

I don't know AltCSS, and google can't help me with the 3 first entries, hehehe. What is AltCSS?

**Pull request closed without merging**
