### PR TITLE
Fixing ASIO4ALL overload when listening public rooms

### PR DESCRIPTION
**Pull request by elieserdejesus**
- Decoding small mp3 packets to avoid blocking the audio thread
- Refactoring some bad named signal/slots

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , I can't reproduce the bug described in #430 in my machine, but I'm suspecting the mp3 decoder. I changed the code to decode small mp3 packets and avoid freeze the audio thread (ASIO4ALL) while decoding. In my tests it's working ok with 32/64 bits and with small and large audio buffer sizes (128 - 2048).

Can you test this branch in your machine to see if ASI04ALL is overloaded?

**Comment by jonjamcam** [comment]
@elieserdejesus I can only compile x32 in my system.

**Comment by jonjamcam** [comment]
@elieserdejesus Tested, but I still have the problem. I checked 2.0.13 and I can confirm it was the last version that was working OK. If you need I can do a video so you can see the problem better.

**Comment by elieserdejesus** [comment]
@jonjamcam 
> but I still have the problem. 

The 2 problems? Audio crackles and red ASIO4ALL icon?

**Comment by jonjamcam** [comment]
>The 2 problems?

Just the ASIO4ALL icon problem. No crackles in my tests so far.

**Comment by elieserdejesus** [comment]
@jonjamcam , can you test again? I'm using another approach to avoid blocking the audio/ASIO4ALL thread.

[Jamtaba2.zip](https://github.com/elieserdejesus/JamTaba/files/434723/Jamtaba2.zip)

**Comment by jonjamcam** [comment]
@elieserdejesus This last version solves the overload problem, but the audio of the room skips (like a scratched CD) and after a while jamtaba crashes.

**Comment by elieserdejesus** [comment]
@jonjamcam , can you test/compile this branch again? I added some log messages to try understand the problem.

**Comment by jonjamcam** [comment]
@elieserdejesus Works pretty good now. No more skipped sound and no crash. This are the messages:

image

**Comment by elieserdejesus** [comment]
Nice news @jonjamcam , I tested in Linux and is working too. I'm attaching the x64 version:
[Jamtaba2.zip](https://github.com/elieserdejesus/JamTaba/files/437385/Jamtaba2.zip)

**Comment by jonjamcam** [comment]
@elieserdejesus x64 working OK! Good Job!

**Comment by elieserdejesus** [comment]
Thanks @jonjamcam !

**Comment by jonjamcam** [comment]
@elieserdejesus I tested a compiled version (32bit standalone) in my old Pentium 4 XP machine (1 processor) and the listen function almost freezes the PC. I don't know if anyone is using XP these days, My question this PR will work on multiprocessor computers only?

**Comment by elieserdejesus** [comment]
@jonjamcam , the current solution works better in multiprocessor computers, but this is not mandatory. At moment Jamtaba is using different threads to play audio (portaudio), decode mp3 and GUI (Qt thread). Qt use another threads internally to run network code too. 

In multiprocessor computers these threads can run in different cores, and the result is very good from a processor usage point of view. In a mono core computer all threads will run/compete for the only processor. These threads will be scheduled in the processor, every thread using a little time slice.

So, in theory these multi thread solutions will work in mono core processors, but the result can be not so good :(

**Comment by jonjamcam** [comment]
I see. I like the thread separation. My win7 Laptop is rather old (2 cores), but Jamtaba works like a Charm, specially now.

 Anyway it's only the listen function that has problems. And I suspect XP is not longer used except for old software compatibility, so not big deal.

**Pull request merged**
