### PR TITLE
Spanish translation files

### PR DESCRIPTION
**Pull request by jonjamcam**

### CODE REVIEW

**Comment by jonjamcam** [comment]
@elieserdejesus @teamikl This is my first revision of the translation.

**Comment by teamikl** [comment]
@jonjamcam 
ya, good job and thank you for review!

This commit had contained update ja_JP.*
I need to re-think the translation guide

Because, lupdate PROJECTS/Jamtaba.pro will update all *.ts files
so could not do just `git add ./translations`

For this PR, can you reset that commit? if you use git command
```
git reset HEAD~ -- ./translations/ja_JP.*
git commit --amend
git push -f origin master
```
NOTE: `origin` is up to your remote's configuration

**Comment by jonjamcam** [comment]
sure @teamikl . must I delete the commit first? or just do another PR over?

**Comment by teamikl** [comment]
@jonjamcam 
do you use command line git or other git tool ?

you can do that on this PR, 
when push the changes to remote, GitHub will replace automatically.

I am reading lupdate command option,
there was lupdate -ts (TS file path) that override TRANSLATIONS.
I will mention this in ./translations/README.md

**Comment by jonjamcam** [comment]
did first

git reset HEAD~ -- ./translations/ja_JP.*

no problem

but then 

git commit --amend

this screen appeared

commit--amend

and I don't know what it means

**Comment by jonjamcam** [comment]
@teamikl it's no problem for me to delete the whole branch and commit again if needed.

**Comment by teamikl** [comment]
@jonjamcam 

now that is no problem
- modified: src/resources/jamtaba.qrc
- new file: translations/es_CL.qm
- new file: translations/es_CL.ts
- modified: translations/translations.pri

is an expected commit.
`Changes not staged for commit:` are modified files but not into commit, you can ignore them.

Now, you can go that commit --amend and push them to remote branch.

NOTE: it's not good to use force option often, but now the side effect is small

**Comment by jonjamcam** [comment]
@teamikl I'm stuck. commit --amend keeps showing the same message. Tried push, but says "everything up to date"

**Comment by teamikl** [comment]
@jonjamcam 

sorry my mistake, it was not master
`git push -f origin master` -> `git push -f origin (branch name)`

**Comment by jonjamcam** [comment]
did

git push -f origin Localize-es_CL

says:

everything up to date

**Comment by teamikl** [comment]
@jonjamcam 

the screen shot was looks ok, but missing reset before commit --amend now?

what does this show? (previous commit log with details)
```
git log --stat -1
```
if that shown 4 files then current branch is ok, push problem
if that contains ja_JP files committed then commit amend was not done.
need to redo those reset/commit --amend/push

**Comment by jonjamcam** [comment]
did

git log --stat -1

stat

**Comment by teamikl** [comment]
@jonjamcam 

so ja_JP.* were not reset, please try again

```
git reset HEAD~ -- ./translations/ja_JP.*
git commit --amend
git push -f origin Localize-es_CL
```

if you saw same https://github.com/elieserdejesus/JamTaba/pull/280#issuecomment-206097277 on commit --amend, that should work

**Comment by jonjamcam** [comment]
Yes same msg. My problem is what do I do when the message appear. It looks it's asking me to write the commit name, but how I do that? that's the part I'm missing

**Comment by teamikl** [comment]
@jonjamcam 
was this the first time you do git commit on console?

the first screenshot is edit commit message.
it's on console based editor called `vim` it's hard to explain how to use vim
if you see the same msg then you can type (ESC) and `:wq`   (write and quit commands)


A. open notepad to edit commit message
```
> EDITOR=notepad git commit --amend
```
EDITOR is environment variable. you can set if lazy to type it every time,
you can configure git options core.editor section

B. given commit message as command line arguments.
```
> git commit --amend -m "Spanish translation files"
```
this can pass open editor, but this way can not check what files are committed before commit.
so pls use `git status` to check before commit.

C.
or use another GUI based git tools.

**Comment by jonjamcam** [comment]
@teamikl It's not the first time I use the console, but I'm still not familiar with that editor (happened before). Don't worry. I have another solution. I will probably do the PR again tomorrow with a fresh mind. It's easier for me to delete and redo. Have to go to sleep now. Talk to you tomorrow. thx.

**Comment by jonjamcam** [comment]
@teamikl , last try looks it worked. can you please check if the commit is OK now?

**Comment by teamikl** [comment]
@jonjamcam 

Yes, it worked 812231952c1ca40b26ab0ecfd1f923db39156d14 is ok now.

**Comment by jonjamcam** [comment]
thx. Happy now. good night!

**Comment by teamikl** [comment]
@jonjamcam 

late time for you! gnite :night_with_stars: 

Result of this review, todo for me
- ./translations/README.md to mention until make PR (which files to add)

**Comment by teamikl** [comment]
there was another solution

`git commit --amend --no-edit` to not open editor, because your commit already had message.

the open `notepad` was temporary solution, it's not good to use notepad as standard editor.
because of encoding and line format.

**Comment by elieserdejesus** [comment]
@jonjamcam , can I integrate this PR? It's finished, right? Just checking ...

**Comment by jonjamcam** [comment]
>can I integrate this PR? It's finished, right? Just checking ...

Yes It's complete @elieserdejesus .

**Comment by elieserdejesus** [comment]
This PR is Integrated, thanks!

**Pull request closed without merging**
