### PR TITLE
[Looper] Alowing focused layer

### PR DESCRIPTION
**Pull request by elieserdejesus**

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , I implemented the "focused layer" idea you mentioned. It's nice now, very flexible to record.
Can you check if is working as expected in all modes?

**Comment by jonjamcam** [comment]
Works great! THx @elieserdejesus The only issue I see is that you **can** focus locked layers, but you can't record on them. As focus is intended only for recording, locked layers should be exempted from fucus.

**Comment by elieserdejesus** [comment]
@jonjamcam , I fixed the focus in locked layers.

**Comment by jonjamcam** [comment]
cool, it' perfect now! thx.

**Pull request merged**
