### PR TITLE
Fixing wrong values in ASIO buffer size combobox

### PR DESCRIPTION
**Pull request by elieserdejesus**
fixing #474

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , I'm working in the issue #474 . Now when we change the audio driver the buffer size combobox is updated with supported values. Can you test your devices, please?

**Comment by jonjamcam** [comment]
@elieserdejesus Yes, the list is correct as soon as you select the driver:

image

**Comment by elieserdejesus** [comment]
@jonjamcam , just to be shure, can you test the scenario described in the issue #474 ? You reported a initial buffer size of 128 using ASIO4ALL and change to ME-25 after some time. 

What you see when you change from **ASIO4ALL + 128 samples** to ME-25?

**Comment by jonjamcam** [comment]
>What you see when you change from ASIO4ALL + 128 samples to ME-25?

That was actually the test. My computer always uses ASIO4ALL as default driver. So I opened the preferences and and changed to ME-25. The buffers and sample rate changed instantly from 48000/64 to 44100/96

**Comment by elieserdejesus** [comment]
@jonjamcam , I see the values 64 and 96 are the minimum buffer size values for your 2 devices. In this case, I'm worried Jamtaba is just keeping the first item in the combobox.

can you do a last test **ME-25 + 6144 samples** to ASIO4ALL? What value is selected in ASIO4ALL in this case?

I can't do these tests because my ASIO4ALL and my Fast track ultra are showing exactly same buffer size values list.

**Comment by jonjamcam** [comment]
>My computer always uses ASIO4ALL as default driver

@elieserdejesus First let me be more specific on this issue. If the ME-25 is not connected, then ASIO4ALL is the default driver, but if I start Jamtaba with the ME-25 plugged in and turned ON, then the ME-25 acts as default. So the question is **out of the question** :)

>can you do a last test ME-25 + 6144 samples to ASIO4ALL? What value is selected in ASIO4ALL in this case?

Ok. So we start with these values:

image

The buffer value of 6144 is kept even after restart. Now we change driver to ASIO4ALL:

image

The buffer size and Sample Rate shown by default are the minimum (64/44100). Wchange that to other values (2048/48000)

image

Now back to ME-25 again values are the minimum, not the ones I chose before:

image

**Comment by elieserdejesus** [comment]
@jonjamcam, 
> Now back to ME-25 again values are the minimum, not the ones I chose before

Jamtaba is not remembering the "preferred" buffer size for each ASIO driver, but I think this is a good idea for a new feature. Another possibility is use the ASIO preferred buffer size. If I remember correctly asio drivers can report the preferred buffer size. But I think this is another feature/issue.

I think this issue is solved, right? no more problems with invalid buffer size values.

**Comment by jonjamcam** [comment]
> I think this issue is solved, right?

Yes. It's solved.

**Pull request merged**
