### PR TITLE
Allowing Private server Hosting in user machine

### PR DESCRIPTION
**Pull request by elieserdejesus**
- Allowing private servers
- Opening the server port in user router using UpNp protocol (if enabled)
- The server is basic (but usefull) at moment
   - The server is missing passwords, ip masking, admin kick, read .cfg file, etc.

To compile this PR is mandatory re-download the [static libs](https://www.dropbox.com/s/qckwsmaqlditwpb/JamTaba-static-libs.zip?dl=0) (updated to include **miniupnp** lib): 

- [x] Implement votes

image

image

image

### CODE REVIEW

**Comment by jonjamcam** [comment]
Compiling OK here @elieserdejesus

**Comment by elieserdejesus** [comment]
@jonjamcam , issues fixed! Thanks for testing and reporting.

The UPnP protocol is working in your router? The port 2049 was automatically opened?

**Comment by jonjamcam** [comment]
> The UPnP protocol is working in your router? The port 2049 was automatically opened?

yes @elieserdejesus :+1:

image

**Comment by elieserdejesus** [comment]
thanks @jonjamcam , I will merge these 1577 commits 😄

**Comment by elieserdejesus** [comment]
@jonjamcam , @pljones , a new beta is available. I think this is the last beta. Please play some jams using this beta to see if is stable enough to release. 

Thanks for your collaboration: https://github.com/elieserdejesus/JamTaba/releases/tag/v2.1.4-beta.2

**Pull request merged**
