### PR TITLE
[WIP] Receiving midi messages generated by Vst Plugins

### PR DESCRIPTION
**Pull request by elieserdejesus**
- [x] Receiving midi messages generated by vst plugins.

- [x] When testing using a Arpeggiator followed by some VSTi in the chain: Jamtaba is sending the midi message to both (I can hear the note played by the VSTi); When I run same test in Reaper just the midi messages generated by the arpeggiator are played. The original midi message (generated in the midi controller) is not played by VSTi, only the messages generated by the arpeggiator are played.

- [x] In Reaper the arpeggiator works with the transport stopped. In Jamtaba this is not working, the arpeggiator works only when I entered in a server. This is bad because is not possible hear the arppegiator before enter in a server.

- [x] Bug in plugins order: 1) Insert a arpeggiator in first slot; 2) insert a VSTi in 2nd slot, works fine. 3) remove the arppegiator from 1st slot; 4) insert the same arppegiator in the first slot again, and will not work. In the gui the arpeggiator is in the first slot, but is second inside jamtaba, and this will break the midi chain.

- [x] Some plugins can't work in a VSTi chain. For example, 4FrontBass is not generating midi messages, and the next VSTi plugins in the chain will produce no sound. I tested the same plugin in Reaper and works, I suppose reaper is doing some magic behind scenes.

- [x] Problem when testint kontakt with the option "send incomming messages" enabled. Kontakt is receiving your own messages.

This PR implements the issue #367.

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , can you help testing this branch, please?  
I drastically changed the midi code to allow the #367 feature. I tested some cases here and all working, but is necessary test with more plugins.

 If possible please test:
- [ ] plugins like Improvisator or Arppegiators. 
- [ ] try to remove and add the plugins in different slots to test the new VSTi chain code.
- [ ] Try to combine VSTi and VSTs too. For example, using a VSTi followed by a reverb or delay.

**Comment by jonjamcam** [comment]
@elieserdejesus I just tested this branch and it works really good!. 

Tested improvisator, kontakt and nexus. Fantastic! THX for all the work!

**Comment by jonjamcam** [comment]
Observation 1: testing Improvisator sending out harmony data. For plugins like Nexus that receive in OMNI mode by default (all channels received play at once) the notes are recognized OK.

image

But for plugins that route different Midi channels to different sounds banks (like B4, M1) the chords are separated and sent one note to one different channel. I'm not sure if this is an improvisator problem. I will test with other plugs and report.

**Comment by jonjamcam** [comment]
> Try to combine VSTi and VSTs too. For example, using a VSTi followed by a reverb or delay.

This is a perfect chain for example:

image

Inside a ninjam room. 1st improvisator is locked to the tempo sending two midi chords to monopoly, then all the audio is processed by Specton. 

WORKING PERFECT!

**Comment by jonjamcam** [comment]
>Try to combine VSTi and VSTs too. For example, using a VSTi followed by a reverb or delay.

image

In this example Audio from the laptop mic is converted to midi note using DSPtrigger for drum triggering in Kontakt (in this case, the snare)

WORKING FINE!

**Comment by elieserdejesus** [comment]
Really thanks @jonjamcam , it's nice see all this tools working fine. I spend a lot of time trying understand how Reaper is chaining midi messages (Reaper chaining is perfect to play online using VSTi). I think now we have a really cool solution for VSTi.

I will merge this PR, thanks again for your help!

**Comment by jonjamcam** [comment]
All credits go to you @elieserdejesus . Your work is really a piece of art. Thx again for all you're doing with Jamtaba!

**Pull request merged**
