### PR TITLE
Implement CC license link idea

### PR DESCRIPTION
**Pull request by teamikl**
- [x] ~~get locale string, system locale or user selected language~~
- [x] ~~click link will call shell exec on windows, need review for security~~
- [x] CC license version 3.0 and 4.0 links worked with the same url format. 

implement idea on #291.

### CODE REVIEW

**Comment by teamikl** [comment]
about security of QMessageBox

QMessageBox the default [textFormat](http://doc.qt.io/qt-5/qmessagebox.html#textFormat-prop) is [Qt::AutoText](http://doc.qt.io/qt-5/qt.html#TextFormat-enum)
if setText detect html tag then set format Qt::RichText implicitly then
click a hyperlink with Qt::RichText will call shell execute on windows platform.

current JamTaba code also may have this.
showing NINJAM license text case in JamTaba:
- only server admin can set the license text (unless the server has security hole)
- require user's click action to invoke

other effects?
- [ ] other platforms openUrl implementation
- [ ] other use case: QMessageBox, or everywhere remote strings shown in QLabel widgets

here proof code:
https://gist.github.com/teamikl/65e870322c60567fb1371dcaa93b9135

**Comment by teamikl** [comment]
> get locale string, system locale or user selected language

This was not a possible scenario.
user selected languages are only available if translation resource exists.
so use getTranslation info here was useless, others will see English which not equal to their locale.

> click link will call shell exec on windows, need review for security

I added escape code to avoid this (like `s/</&lt;/')
so I will not research details about this, I check this task as consumed
with modify it strike styles (canceled task).

**Comment by teamikl** [comment]
@elieserdejesus 
all scheduled tasks has completed. now it's stage for test/review, please check.

**Comment by jonjamcam** [comment]
@teamikl Just tested. The link is working, but the language chosen is the one of my system (es) and not the one Jamtaba is using. I think this is good enough. In my opinion no need to change it.

**Comment by elieserdejesus** [comment]
@teamikl and @jonjamcam , tested here and is working. The link point to the portuguese licence translation here.

**Comment by elieserdejesus** [comment]
@teamikl , can I integrate this PR in master? I check the commits and see no issues to review, it's nice for me.

**Comment by teamikl** [comment]
@elieserdejesus 
Yes, if review/tested was passed. please!

**Comment by elieserdejesus** [comment]
It's integrated in master, thanks!

**Pull request closed without merging**
