### PR TITLE
[WIP] Updating translation files

### PR DESCRIPTION
**Pull request by elieserdejesus**
- [x] update the english file
- [x] update the portuguese file
- [x] update the spanish file
- [ ] update the japanese file
- [ ] update the french file

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@teamikl and @jonjamcam , it's time to update the translation files. The updated .ts files are commited in this PR branch. Thanks in advance!

**Comment by jonjamcam** [comment]
@elieserdejesus The "no input" source text is missing" in my es_CL.ts. It's currently not being translated.

**Comment by teamikl** [comment]
@elieserdejesus 
will you keep this branch as long life branch?
or just temporary for this PR as usual ?

I will maintain this branch for ja_JP.ts file, keep it always pickable latest resource.
https://github.com/teamikl/JamTaba/tree/translate-ja_JP

can you pick the file ? or tell me if I could commit to this PR branch.

----

I got a suggestion for lupdate timing workflow
it's can be anytime when when new translatable resource were added.
updated ts file (without translation) also can be committed.
then for developer, anytime can do the translation task on own branch.
then can be merged on this update translation PR branch.

NOTE: It's lazy to check this stuff every times.
so this is an option, git has hook commit time or before push.
run lupdate every commit time, it should safe. no changes if nothing update.
Manual lupdate is also ok, run lupdate when noticed is enough. no need so strict rules here.

**Comment by elieserdejesus** [comment]
@jonjamcam and @teamikl 
> The "no input" source text is missing"

My bad, the problem is fixed in this branch. Please pull the new commits in this branch to get TS file including the "no input" text.

> will you keep this branch as long life branch? or just temporary for this PR as usual ?

Just temporary.

> can you pick the file ? or tell me if I could commit to this PR branch.

I can pick the file in your branch, but please add a comment in the **translations PR** so I will receive a "translation done!" notification.

**Comment by jonjamcam** [comment]
@elieserdejesus I'm confused. How do I get my commit pushed here? looks I did another PR (https://github.com/elieserdejesus/JamTaba/pull/339).

**Comment by jonjamcam** [comment]
@elieserdejesus . My translation is done. Here's the branch https://github.com/jonjamcam/JamTaba/tree/translate-es_CL

**Comment by elieserdejesus** [comment]
thanks @jonjamcam , your file is merged in this branch. Please check if the merge is ok, I see you changed/improved some phrases.

**Comment by elieserdejesus** [comment]
ops, I think my merge was not really a merge. My bad, I will fix soon:
image

**Comment by elieserdejesus** [comment]
I hope it's fixed now, sorry for the mess.

**Comment by jonjamcam** [comment]
>I see you changed/improved some phrases.

Yes. The changes work better in context now.

**Comment by teamikl** [comment]
@elieserdejesus 
translate done now
https://github.com/teamikl/JamTaba/tree/translate-ja_JP

I took another steps to update existing translate-ja_JP branch,
so I note this the ja_JP.ts file made by following steps. (this is for my situation only)

- `git checkout updating-translations-files`
- translate
- `git checkout translate-ja_JP`
- `git merge updating-translations-files`

**Comment by elieserdejesus** [comment]
@teamikl  and @jonjamcam , the TS files are integrated in master. Unfortunally I have some conflicts when integrating, so the easy solution was just a manual copy/paste for TS files, 

In next release or translations tasks we need improve this workflow to something more clean. 

Thanks for your help!

**Comment by teamikl** [comment]
@elieserdejesus 
no problem, let's have pre discussion before start translation tasks next time.
for now just passed this by ad-hoc solution, focus on release v2.14.0
then improve workflow next chance.

**Pull request closed without merging**
