### PR TITLE
Jamataba supplemental backup geolocation server complete implementation solves #1146

### PR DESCRIPTION
**Pull request by fab672000**
another 10000 requests a month to use for our community!

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@fab672000 , the git workflow is very confuse. As you can see in this PR you have many old commits, not only the commits related with your new PR. 

Can you try a clean PR, please?

**Comment by fab672000** [comment]
Actually I have reset hard my branch on upstream before starting another set of changes
I don't understand why you still get everything, is it possible that it could on your PR side?

**Comment by fab672000** [comment]
I used this below before i made new changes:
git remote update
# the double hyphen ensures that upstream/master is
# considered as a revision and not confused as a path
git reset --hard upstream/master --

**Comment by fab672000** [comment]
I redid it with also forcing a git push -f on a different branch and it seems to work better, also reduced the number of diffs to minimum. 
The history never changes uin the PR (it shows 25 commits) but the diff is only the 3 file changes.

**Comment by fab672000** [comment]
Completely redid the PR and my master branch, you should see only one commit!

**Pull request closed without merging**
