### PR TITLE
[WIP] Dropping minimode

### PR DESCRIPTION
**Pull request by elieserdejesus**
solving  #676, #669

- [x] Dropping mini mode
- [x] Adding window resize submenu in View menu
- [x] Storing and remembering window size (both standalone and VST)

- [x] The Vst plugin keeps the square (4:3 ?) aspect ratio when resized. It could be better if the aspect ratio was a little more rectangle shaped, like on the standalone

- [x] Local tracks are small all the time in the vst plugin version, but I noticed the standalone resize them to a good size when maximized

- [x] When you connect to a server the "big local tracks" are reduced again, and they keep the small size until restart

### CODE REVIEW

**Comment by elieserdejesus** [comment]
@jonjamcam , can you help testing this PR? I dropped minimode and added menu entries to resize the VST window.

[Jamtaba 2 (64 bits) installer.zip](https://github.com/elieserdejesus/JamTaba/files/728009/Jamtaba.2.64.bits.installer.zip)

**Comment by jonjamcam** [comment]
My tests show:

1. The Vst plugin keeps the square (4:3 ?) aspect ratio when resized. This is a snap from a 1920x1080 TV.:

image

 It could be better if the aspect ratio was a little more _rectangle shaped_, like on the standalone version (if possible):

image

2.- The local tracks are small all the time in the vst plugin version, but I noticed the standalone resize them to a good size when maximized. If the plugin could have the same feature when the size is larger than 800x600 (or any other resolution that's not considered small) it would be better for larger screens:

image

 Overall the result is very good. Big improvement, specially for big screens.

**Comment by elieserdejesus** [comment]
@jonjamcam , I fixed the issues you commented before. It's much better now. Improved aspect ratio in plugin window, the resize menu entries are disabled when is not possible change the window size, the 2 collumn layout (public servers) is used always horizontal space is enough, the local tracks are always wide, except in plugins (VST/AU) when minimum window size is used and there are 2 local channels. 

Can you run a final inspection, please?

[Jamtaba 2 (64 bits) installer.zip](https://github.com/elieserdejesus/JamTaba/files/731195/Jamtaba.2.64.bits.installer.zip)

**Comment by jonjamcam** [comment]
> Can you run a final inspection, please?

Works great. I tested in the TV and the maximun size is perfect. Local tracks are correct for each size now.

**Pull request closed without merging**
